use dinoco_compiler::{Database, ParsedSchema};

use super::helpers::render_connection_url;

const GENERATED_FILE_BANNER: &str = "// ==============================================================\n\
// =================== DINOCO MANAGED FILE =======================\n\
// ==============================================================\n\
// This file is generated and managed by Dinoco.\n\
// Do not edit this file manually.\n\
// Any manual changes will be overwritten the next time Dinoco runs.\n\
// ==============================================================\n\n";

pub(crate) fn render_dinoco_module(schema: &ParsedSchema) -> String {
    let adapter = match schema.config.database {
        Database::Mysql => "MySqlAdapter",
        Database::Postgresql => "PostgresAdapter",
        Database::Sqlite => "SqliteAdapter",
    };
    let database_url = render_connection_url(&schema.config.database_url);
    let read_replicas = if schema.config.read_replicas.is_empty() {
        "vec![]".to_string()
    } else {
        let values = schema.config.read_replicas.iter().map(render_connection_url).collect::<Vec<_>>().join(", ");

        format!("vec![{values}]")
    };

    format!(
        "{GENERATED_FILE_BANNER}use dinoco::{{DinocoClient, DinocoResult}};\nuse ::dinoco_engine::{{{adapter}}};\n\npub mod models;\npub use models::*;\n\npub async fn create_connection() -> DinocoResult<DinocoClient<{adapter}>> {{\n    DinocoClient::<{adapter}>::new({database_url}, {read_replicas}).await\n}}\n"
    )
}
