use dinoco_compiler::{Database, ParsedSchema};

use super::helpers::render_connection_url;

const GENERATED_FILE_BANNER: &str = "// ==============================================================\n\
// =================== DINOCO MANAGED FILE =======================\n\
// ==============================================================\n\
// This file is generated and managed by Dinoco.\n\
// Do not edit this file manually.\n\
// Any manual changes will be overwritten the next time Dinoco runs.\n\
// ==============================================================\n\n";
const GENERATED_FILE_LINTS: &str = "#![allow(dead_code)]\n#![allow(non_camel_case_types)]\n#![allow(non_snake_case)]\n#![allow(non_upper_case_globals)]\n#![allow(unused_imports)]\n#![allow(unused_variables)]\n\n";

fn render_sqlite_url_base_resolver() -> String {
    String::from(
        "fn __dinoco_sqlite_base_url(url: String) -> String {\n    fn is_windows_absolute(path: &str) -> bool {\n        let bytes = path.as_bytes();\n\n        bytes.len() > 2\n            && bytes[1] == b':'\n            && (bytes[2] == b'/' || bytes[2] == b'\\\\')\n            && bytes[0].is_ascii_alphabetic()\n    }\n\n    if !url.starts_with(\"file:\") {\n        return url;\n    }\n\n    let raw = &url[\"file:\".len()..];\n\n    if raw.is_empty()\n        || raw == \":memory:\"\n        || raw.starts_with('/')\n        || raw.starts_with(\"//\")\n        || is_windows_absolute(raw)\n    {\n        return url;\n    }\n\n    let (path_part, suffix) = match raw.split_once('?') {\n        Some((path, query)) => (path, format!(\"?{}\", query)),\n        None => (raw, String::new()),\n    };\n\n    if path_part == \":memory:\"\n        || path_part.starts_with(\"dinoco/\")\n        || path_part.starts_with(\"./dinoco/\")\n    {\n        return url;\n    }\n\n    let normalized_relative = path_part.strip_prefix(\"./\").unwrap_or(path_part);\n    let normalized_path = std::path::Path::new(\"dinoco\").join(normalized_relative);\n    let normalized_path = normalized_path.to_string_lossy().replace('\\\\', \"/\");\n\n    format!(\"file:{}{}\", normalized_path, suffix)\n}\n",
    )
}

pub(crate) fn render_dinoco_module(schema: &ParsedSchema) -> String {
    let adapter = match schema.config.database {
        Database::Mysql => "MySqlAdapter",
        Database::Postgresql => "PostgresAdapter",
        Database::Sqlite => "SqliteAdapter",
    };
    let database_url = render_connection_url(&schema.config.database_url);
    let read_replicas = if schema.config.read_replicas.is_empty() {
        "vec![]".to_string()
    } else {
        let values = schema.config.read_replicas.iter().map(render_connection_url).collect::<Vec<_>>().join(", ");

        format!("vec![{values}]")
    };
    let mut output = format!(
        "{GENERATED_FILE_BANNER}{GENERATED_FILE_LINTS}use dinoco::{{DinocoClient, DinocoClientConfig, DinocoResult, {adapter}}};\n\npub mod models;\npub use models::*;\n\n"
    );

    if matches!(schema.config.database, Database::Sqlite) {
        output.push_str(&render_sqlite_url_base_resolver());
        output.push('\n');
    }

    output.push_str("pub async fn create_connection(config: DinocoClientConfig) -> DinocoResult<DinocoClient<");
    output.push_str(adapter);
    output.push_str(">> {\n");

    if matches!(schema.config.database, Database::Sqlite) {
        output.push_str("    let database_url = __dinoco_sqlite_base_url(");
        output.push_str(&database_url);
        output.push_str(");\n");
    }

    output.push_str("    DinocoClient::<");
    output.push_str(adapter);
    output.push_str(">::new(");
    if matches!(schema.config.database, Database::Sqlite) {
        output.push_str("database_url");
    } else {
        output.push_str(&database_url);
    }
    output.push_str(", ");
    output.push_str(&read_replicas);
    output.push_str(", config).await\n}\n");

    output
}
