use dinoco_compiler::ParsedSchema;

use super::helpers::pascal_case;

const GENERATED_FILE_BANNER: &str = "// ==============================================================\n\
// =================== DINOCO MANAGED FILE =======================\n\
// ==============================================================\n\
// This file is generated and managed by Dinoco.\n\
// Do not edit this file manually.\n\
// Any manual changes will be overwritten the next time Dinoco runs.\n\
// ==============================================================\n\n";

pub(crate) fn render_enums(schema: &ParsedSchema) -> String {
    let mut output = String::from(GENERATED_FILE_BANNER);

    for item in &schema.enums {
        output.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
        output.push_str(&format!("pub enum {} {{\n", item.name));

        for value in &item.values {
            output.push_str(&format!("    {},\n", pascal_case(value)));
        }

        output.push_str("}\n\n");
        output.push_str(&format!("impl TryFrom<dinoco::DinocoValue> for {} {{\n", item.name));
        output.push_str("    type Error = dinoco::DinocoError;\n\n");
        output.push_str("    fn try_from(value: dinoco::DinocoValue) -> Result<Self, Self::Error> {\n");
        output.push_str("        let value = match value {\n");
        output.push_str("            dinoco::DinocoValue::String(value) => value,\n");
        output.push_str("            dinoco::DinocoValue::Bytes(value) => String::from_utf8(value)\n");
        output.push_str(
            "                .map_err(|_| dinoco::DinocoError::ParseError(\"Invalid UTF-8 enum value\".into()))?,\n",
        );
        output.push_str(
            "            _ => return Err(dinoco::DinocoError::ParseError(\"Expected enum string value\".into())),\n",
        );
        output.push_str("        };\n\n");
        output.push_str("        match value.as_str() {\n");

        for value in &item.values {
            output.push_str(&format!("            {:?} => Ok(Self::{}),\n", value, pascal_case(value)));
        }

        output.push_str(&format!(
            "            _ => Err(dinoco::DinocoError::ParseError(format!(\"Invalid value '{{}}' for enum {}\", value))),\n",
            item.name
        ));
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");
        output.push_str(&format!("impl dinoco::IntoDinocoValue for {} {{\n", item.name));
        output.push_str("    fn into_dinoco_value(self) -> dinoco::DinocoValue {\n");
        output.push_str("        dinoco::DinocoValue::String(match self {\n");

        for value in &item.values {
            output.push_str(&format!("            Self::{} => {:?}.to_string(),\n", pascal_case(value), value));
        }

        output.push_str("        })\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");
    }

    output
}
