[package]
name = "dinoco_engine"
version = "2.0.0"
edition = "2024"
license = "Apache-2.0"
description = "Database adapters, query execution, and migration engine components for Dinoco."
homepage = "https://dinoco.io"
repository = "https://github.com/dinoco-rs/dinoco"
readme = "../../crates.md"
keywords = ["orm", "database", "sql", "adapters", "migrations"]

[dependencies]
tokio = { version = "1.50.0", features = ["full", "rt-multi-thread"] }

async-trait = "0.1.89"
async-stream = "0.3.6"
futures = "0.3.32"

deadpool-sqlite = "0.13"
rusqlite = { version = "0.38", features = [
	"bundled",
	"chrono",
	"hooks",
	"serde_json",
] }
deadpool-postgres = "0.14"
tokio-postgres = { version = "0.7", features = [
	"with-chrono-0_4",
	"with-serde_json-1",
] }
mysql_async = { version = "0.36", features = ["chrono"] }
mysql_common = { version = "0.35", features = ["chrono"] }
anyhow = "1.0.103"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
