CREATE TABLE "Player" ("id" TEXT PRIMARY KEY, "nicknameColor" TEXT NOT NULL DEFAULT '#ffffff', "nickname" TEXT NOT NULL, "password" TEXT NOT NULL, "levelStepRemaining" INTEGER NOT NULL DEFAULT 600, "levelStep" INTEGER NOT NULL DEFAULT 0, "level" INTEGER NOT NULL DEFAULT 0, "stars" INTEGER NOT NULL DEFAULT 0, "sleep" INTEGER NOT NULL DEFAULT 7200, "sleepPercent" INTEGER NOT NULL DEFAULT 100, "health" INTEGER NOT NULL DEFAULT 360, "healthPercent" INTEGER NOT NULL DEFAULT 100, "thirst" INTEGER NOT NULL DEFAULT 900, "thirstPercent" INTEGER NOT NULL DEFAULT 100, "hunger" INTEGER NOT NULL DEFAULT 1500, "hungerPercent" INTEGER NOT NULL DEFAULT 100, "email" TEXT NOT NULL, "emailVerified" BOOLEAN NOT NULL DEFAULT FALSE, "watchedTutorial" BOOLEAN NOT NULL DEFAULT FALSE, "x" REAL NOT NULL, "y" REAL NOT NULL, "z" REAL NOT NULL, "heading" REAL NOT NULL, "office" TEXT CHECK (office IN ('developer', 'director', 'administrator', 'moderator', 'helper', 'youtuber', 'member')) NOT NULL, "gender" TEXT CHECK (gender IN ('male', 'female')) NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE "CharacterOutfit" ("id" TEXT PRIMARY KEY, "component" INTEGER NOT NULL, "drawable" INTEGER NOT NULL, "texture" INTEGER NOT NULL, "playerId" TEXT, CONSTRAINT "fk_CharacterOutfit_playerId" FOREIGN KEY ("playerId") REFERENCES "Player" ("id") ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE "Subscription" ("id" TEXT PRIMARY KEY, "color" TEXT NOT NULL DEFAULT '#ffd900', "endAt" DATETIME NOT NULL, "startedAt" DATETIME NOT NULL, "playerId" TEXT, CONSTRAINT "fk_Subscription_playerId" FOREIGN KEY ("playerId") REFERENCES "Player" ("id") ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE "PlayerVerify" ("id" TEXT PRIMARY KEY, "email" TEXT NOT NULL, "code" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "playerId" TEXT, CONSTRAINT "fk_PlayerVerify_playerId" FOREIGN KEY ("playerId") REFERENCES "Player" ("id") ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE "PlayerResetPassword" ("id" TEXT PRIMARY KEY, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "playerId" TEXT, CONSTRAINT "fk_PlayerResetPassword_playerId" FOREIGN KEY ("playerId") REFERENCES "Player" ("id") ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE "Character" ("id" TEXT PRIMARY KEY, "father" INTEGER NOT NULL, "mother" INTEGER NOT NULL, "skinFather" INTEGER NOT NULL, "skinMother" INTEGER NOT NULL, "eyebrowsColor" INTEGER NOT NULL, "lipstick" INTEGER NOT NULL, "hair" INTEGER NOT NULL, "hairColor" INTEGER NOT NULL, "bodyHair" INTEGER NOT NULL, "bodyHairColor" INTEGER NOT NULL, "beard" INTEGER NOT NULL, "beardColor" INTEGER NOT NULL, "blush" INTEGER NOT NULL, "makeup" INTEGER NOT NULL, "complexion" INTEGER NOT NULL, "sunDamage" INTEGER NOT NULL, "fleckles" INTEGER NOT NULL, "ageing" INTEGER NOT NULL, "blemishes" INTEGER NOT NULL, "bodyBlemishes" INTEGER NOT NULL, "eyeColor" INTEGER NOT NULL, "lips" REAL NOT NULL, "shapeMix" REAL NOT NULL, "skinMix" REAL NOT NULL, "eyeOpening" REAL NOT NULL, "eyebrows" REAL NOT NULL, "eyebrowsOpacity" REAL NOT NULL, "eyebrowHeight" REAL NOT NULL, "eyebrowDepth" REAL NOT NULL, "noseWidth" REAL NOT NULL, "noseHeight" REAL NOT NULL, "noseLength" REAL NOT NULL, "noseBridge" REAL NOT NULL, "noseTip" REAL NOT NULL, "noseCurvature" REAL NOT NULL, "jawWidth" REAL NOT NULL, "jawHeight" REAL NOT NULL, "chinLength" REAL NOT NULL, "chinPosition" REAL NOT NULL, "chinWidth" REAL NOT NULL, "chinShape" REAL NOT NULL, "cheeksHeight" REAL NOT NULL, "cheeksWidth" REAL NOT NULL, "cheekSize" REAL NOT NULL, "neckSize" REAL NOT NULL, "beardOpacity" REAL NOT NULL, "blemishesOpacity" REAL NOT NULL, "playerId" TEXT, CONSTRAINT "fk_Character_playerId" FOREIGN KEY ("playerId") REFERENCES "Player" ("id") ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE "PlayerToken" ("id" TEXT PRIMARY KEY, "isExpired" BOOLEAN NOT NULL DEFAULT FALSE, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "playerId" TEXT, CONSTRAINT "fk_PlayerToken_playerId" FOREIGN KEY ("playerId") REFERENCES "Player" ("id") ON DELETE CASCADE ON UPDATE CASCADE);