[workspace]
members = [
	"crates/dinoco",
	"crates/dinoco_cli",
	"crates/dinoco_codegen",
	"crates/dinoco_compiler",
	"crates/dinoco_engine",
	"crates/dinoco_formatter",
	"crates/dinoco_vscode",
	"crates/dinoco_derives",
	"crates/dinoco_tests",
	"examples/axum",
	"examples/actix-web",
]

resolver = "3"
