// ==============================================================
// =================== DINOCO MANAGED FILE =======================
// ==============================================================
// This file is generated and managed by Dinoco.
// Do not edit this file manually.
// Any manual changes will be overwritten the next time Dinoco runs.
// ==============================================================

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
#![allow(unused_variables)]

use dinoco::{AdapterDialect, FindAndUpdateModel, InsertModel, IntoDinocoValue, Model, Projection, RelationField, RelationMutationModel, RelationMutationWhere, RelationScalarField, RelationWritePlan, Rowable, ScalarField, UpdateField, UpdateModel};
use super::{player::Player};

#[derive(Debug, Clone, dinoco::serde::Serialize, dinoco::serde::Deserialize, Rowable)]
#[serde(crate = "dinoco::serde")]
pub struct Character {
    pub id: dinoco::Uuid,
    pub father: i64,
    pub mother: i64,
    pub skinFather: i64,
    pub skinMother: i64,
    pub eyebrowsColor: i64,
    pub lipstick: i64,
    pub hair: i64,
    pub hairColor: i64,
    pub bodyHair: i64,
    pub bodyHairColor: i64,
    pub beard: i64,
    pub beardColor: i64,
    pub blush: i64,
    pub makeup: i64,
    pub complexion: i64,
    pub sunDamage: i64,
    pub fleckles: i64,
    pub ageing: i64,
    pub blemishes: i64,
    pub bodyBlemishes: i64,
    pub eyeColor: i64,
    pub lips: f64,
    pub shapeMix: f64,
    pub skinMix: f64,
    pub eyeOpening: f64,
    pub eyebrows: f64,
    pub eyebrowsOpacity: f64,
    pub eyebrowHeight: f64,
    pub eyebrowDepth: f64,
    pub noseWidth: f64,
    pub noseHeight: f64,
    pub noseLength: f64,
    pub noseBridge: f64,
    pub noseTip: f64,
    pub noseCurvature: f64,
    pub jawWidth: f64,
    pub jawHeight: f64,
    pub chinLength: f64,
    pub chinPosition: f64,
    pub chinWidth: f64,
    pub chinShape: f64,
    pub cheeksHeight: f64,
    pub cheeksWidth: f64,
    pub cheekSize: f64,
    pub neckSize: f64,
    pub beardOpacity: f64,
    pub blemishesOpacity: f64,
    pub playerId: Option<dinoco::Uuid>,
}

impl Character {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Default for Character {
    fn default() -> Self {
        Self {
            id: dinoco::Uuid::new(),
            father: 0,
            mother: 0,
            skinFather: 0,
            skinMother: 0,
            eyebrowsColor: 0,
            lipstick: 0,
            hair: 0,
            hairColor: 0,
            bodyHair: 0,
            bodyHairColor: 0,
            beard: 0,
            beardColor: 0,
            blush: 0,
            makeup: 0,
            complexion: 0,
            sunDamage: 0,
            fleckles: 0,
            ageing: 0,
            blemishes: 0,
            bodyBlemishes: 0,
            eyeColor: 0,
            lips: 0.0,
            shapeMix: 0.0,
            skinMix: 0.0,
            eyeOpening: 0.0,
            eyebrows: 0.0,
            eyebrowsOpacity: 0.0,
            eyebrowHeight: 0.0,
            eyebrowDepth: 0.0,
            noseWidth: 0.0,
            noseHeight: 0.0,
            noseLength: 0.0,
            noseBridge: 0.0,
            noseTip: 0.0,
            noseCurvature: 0.0,
            jawWidth: 0.0,
            jawHeight: 0.0,
            chinLength: 0.0,
            chinPosition: 0.0,
            chinWidth: 0.0,
            chinShape: 0.0,
            cheeksHeight: 0.0,
            cheeksWidth: 0.0,
            cheekSize: 0.0,
            neckSize: 0.0,
            beardOpacity: 0.0,
            blemishesOpacity: 0.0,
            playerId: None,
        }
    }
}

pub struct CharacterWhere {
    pub id: ScalarField<String>,
    pub father: ScalarField<i64>,
    pub mother: ScalarField<i64>,
    pub skinFather: ScalarField<i64>,
    pub skinMother: ScalarField<i64>,
    pub eyebrowsColor: ScalarField<i64>,
    pub lipstick: ScalarField<i64>,
    pub hair: ScalarField<i64>,
    pub hairColor: ScalarField<i64>,
    pub bodyHair: ScalarField<i64>,
    pub bodyHairColor: ScalarField<i64>,
    pub beard: ScalarField<i64>,
    pub beardColor: ScalarField<i64>,
    pub blush: ScalarField<i64>,
    pub makeup: ScalarField<i64>,
    pub complexion: ScalarField<i64>,
    pub sunDamage: ScalarField<i64>,
    pub fleckles: ScalarField<i64>,
    pub ageing: ScalarField<i64>,
    pub blemishes: ScalarField<i64>,
    pub bodyBlemishes: ScalarField<i64>,
    pub eyeColor: ScalarField<i64>,
    pub lips: ScalarField<f64>,
    pub shapeMix: ScalarField<f64>,
    pub skinMix: ScalarField<f64>,
    pub eyeOpening: ScalarField<f64>,
    pub eyebrows: ScalarField<f64>,
    pub eyebrowsOpacity: ScalarField<f64>,
    pub eyebrowHeight: ScalarField<f64>,
    pub eyebrowDepth: ScalarField<f64>,
    pub noseWidth: ScalarField<f64>,
    pub noseHeight: ScalarField<f64>,
    pub noseLength: ScalarField<f64>,
    pub noseBridge: ScalarField<f64>,
    pub noseTip: ScalarField<f64>,
    pub noseCurvature: ScalarField<f64>,
    pub jawWidth: ScalarField<f64>,
    pub jawHeight: ScalarField<f64>,
    pub chinLength: ScalarField<f64>,
    pub chinPosition: ScalarField<f64>,
    pub chinWidth: ScalarField<f64>,
    pub chinShape: ScalarField<f64>,
    pub cheeksHeight: ScalarField<f64>,
    pub cheeksWidth: ScalarField<f64>,
    pub cheekSize: ScalarField<f64>,
    pub neckSize: ScalarField<f64>,
    pub beardOpacity: ScalarField<f64>,
    pub blemishesOpacity: ScalarField<f64>,
    pub playerId: ScalarField<String>,
}

pub struct CharacterUpdate {
    pub father: UpdateField<i64>,
    pub mother: UpdateField<i64>,
    pub skinFather: UpdateField<i64>,
    pub skinMother: UpdateField<i64>,
    pub eyebrowsColor: UpdateField<i64>,
    pub lipstick: UpdateField<i64>,
    pub hair: UpdateField<i64>,
    pub hairColor: UpdateField<i64>,
    pub bodyHair: UpdateField<i64>,
    pub bodyHairColor: UpdateField<i64>,
    pub beard: UpdateField<i64>,
    pub beardColor: UpdateField<i64>,
    pub blush: UpdateField<i64>,
    pub makeup: UpdateField<i64>,
    pub complexion: UpdateField<i64>,
    pub sunDamage: UpdateField<i64>,
    pub fleckles: UpdateField<i64>,
    pub ageing: UpdateField<i64>,
    pub blemishes: UpdateField<i64>,
    pub bodyBlemishes: UpdateField<i64>,
    pub eyeColor: UpdateField<i64>,
    pub lips: UpdateField<f64>,
    pub shapeMix: UpdateField<f64>,
    pub skinMix: UpdateField<f64>,
    pub eyeOpening: UpdateField<f64>,
    pub eyebrows: UpdateField<f64>,
    pub eyebrowsOpacity: UpdateField<f64>,
    pub eyebrowHeight: UpdateField<f64>,
    pub eyebrowDepth: UpdateField<f64>,
    pub noseWidth: UpdateField<f64>,
    pub noseHeight: UpdateField<f64>,
    pub noseLength: UpdateField<f64>,
    pub noseBridge: UpdateField<f64>,
    pub noseTip: UpdateField<f64>,
    pub noseCurvature: UpdateField<f64>,
    pub jawWidth: UpdateField<f64>,
    pub jawHeight: UpdateField<f64>,
    pub chinLength: UpdateField<f64>,
    pub chinPosition: UpdateField<f64>,
    pub chinWidth: UpdateField<f64>,
    pub chinShape: UpdateField<f64>,
    pub cheeksHeight: UpdateField<f64>,
    pub cheeksWidth: UpdateField<f64>,
    pub cheekSize: UpdateField<f64>,
    pub neckSize: UpdateField<f64>,
    pub beardOpacity: UpdateField<f64>,
    pub blemishesOpacity: UpdateField<f64>,
    pub playerId: UpdateField<String>,
}

pub struct CharacterRelationWhere {
    pub id: RelationScalarField<String>,
    pub father: RelationScalarField<i64>,
    pub mother: RelationScalarField<i64>,
    pub skinFather: RelationScalarField<i64>,
    pub skinMother: RelationScalarField<i64>,
    pub eyebrowsColor: RelationScalarField<i64>,
    pub lipstick: RelationScalarField<i64>,
    pub hair: RelationScalarField<i64>,
    pub hairColor: RelationScalarField<i64>,
    pub bodyHair: RelationScalarField<i64>,
    pub bodyHairColor: RelationScalarField<i64>,
    pub beard: RelationScalarField<i64>,
    pub beardColor: RelationScalarField<i64>,
    pub blush: RelationScalarField<i64>,
    pub makeup: RelationScalarField<i64>,
    pub complexion: RelationScalarField<i64>,
    pub sunDamage: RelationScalarField<i64>,
    pub fleckles: RelationScalarField<i64>,
    pub ageing: RelationScalarField<i64>,
    pub blemishes: RelationScalarField<i64>,
    pub bodyBlemishes: RelationScalarField<i64>,
    pub eyeColor: RelationScalarField<i64>,
    pub lips: RelationScalarField<f64>,
    pub shapeMix: RelationScalarField<f64>,
    pub skinMix: RelationScalarField<f64>,
    pub eyeOpening: RelationScalarField<f64>,
    pub eyebrows: RelationScalarField<f64>,
    pub eyebrowsOpacity: RelationScalarField<f64>,
    pub eyebrowHeight: RelationScalarField<f64>,
    pub eyebrowDepth: RelationScalarField<f64>,
    pub noseWidth: RelationScalarField<f64>,
    pub noseHeight: RelationScalarField<f64>,
    pub noseLength: RelationScalarField<f64>,
    pub noseBridge: RelationScalarField<f64>,
    pub noseTip: RelationScalarField<f64>,
    pub noseCurvature: RelationScalarField<f64>,
    pub jawWidth: RelationScalarField<f64>,
    pub jawHeight: RelationScalarField<f64>,
    pub chinLength: RelationScalarField<f64>,
    pub chinPosition: RelationScalarField<f64>,
    pub chinWidth: RelationScalarField<f64>,
    pub chinShape: RelationScalarField<f64>,
    pub cheeksHeight: RelationScalarField<f64>,
    pub cheeksWidth: RelationScalarField<f64>,
    pub cheekSize: RelationScalarField<f64>,
    pub neckSize: RelationScalarField<f64>,
    pub beardOpacity: RelationScalarField<f64>,
    pub blemishesOpacity: RelationScalarField<f64>,
    pub playerId: RelationScalarField<String>,
}

impl CharacterRelationWhere {
    pub fn new(relation_name: &'static str) -> RelationMutationWhere<Self> {
        RelationMutationWhere::new(Self {
            id: RelationScalarField::new(relation_name, "id"),
            father: RelationScalarField::new(relation_name, "father"),
            mother: RelationScalarField::new(relation_name, "mother"),
            skinFather: RelationScalarField::new(relation_name, "skinFather"),
            skinMother: RelationScalarField::new(relation_name, "skinMother"),
            eyebrowsColor: RelationScalarField::new(relation_name, "eyebrowsColor"),
            lipstick: RelationScalarField::new(relation_name, "lipstick"),
            hair: RelationScalarField::new(relation_name, "hair"),
            hairColor: RelationScalarField::new(relation_name, "hairColor"),
            bodyHair: RelationScalarField::new(relation_name, "bodyHair"),
            bodyHairColor: RelationScalarField::new(relation_name, "bodyHairColor"),
            beard: RelationScalarField::new(relation_name, "beard"),
            beardColor: RelationScalarField::new(relation_name, "beardColor"),
            blush: RelationScalarField::new(relation_name, "blush"),
            makeup: RelationScalarField::new(relation_name, "makeup"),
            complexion: RelationScalarField::new(relation_name, "complexion"),
            sunDamage: RelationScalarField::new(relation_name, "sunDamage"),
            fleckles: RelationScalarField::new(relation_name, "fleckles"),
            ageing: RelationScalarField::new(relation_name, "ageing"),
            blemishes: RelationScalarField::new(relation_name, "blemishes"),
            bodyBlemishes: RelationScalarField::new(relation_name, "bodyBlemishes"),
            eyeColor: RelationScalarField::new(relation_name, "eyeColor"),
            lips: RelationScalarField::new(relation_name, "lips"),
            shapeMix: RelationScalarField::new(relation_name, "shapeMix"),
            skinMix: RelationScalarField::new(relation_name, "skinMix"),
            eyeOpening: RelationScalarField::new(relation_name, "eyeOpening"),
            eyebrows: RelationScalarField::new(relation_name, "eyebrows"),
            eyebrowsOpacity: RelationScalarField::new(relation_name, "eyebrowsOpacity"),
            eyebrowHeight: RelationScalarField::new(relation_name, "eyebrowHeight"),
            eyebrowDepth: RelationScalarField::new(relation_name, "eyebrowDepth"),
            noseWidth: RelationScalarField::new(relation_name, "noseWidth"),
            noseHeight: RelationScalarField::new(relation_name, "noseHeight"),
            noseLength: RelationScalarField::new(relation_name, "noseLength"),
            noseBridge: RelationScalarField::new(relation_name, "noseBridge"),
            noseTip: RelationScalarField::new(relation_name, "noseTip"),
            noseCurvature: RelationScalarField::new(relation_name, "noseCurvature"),
            jawWidth: RelationScalarField::new(relation_name, "jawWidth"),
            jawHeight: RelationScalarField::new(relation_name, "jawHeight"),
            chinLength: RelationScalarField::new(relation_name, "chinLength"),
            chinPosition: RelationScalarField::new(relation_name, "chinPosition"),
            chinWidth: RelationScalarField::new(relation_name, "chinWidth"),
            chinShape: RelationScalarField::new(relation_name, "chinShape"),
            cheeksHeight: RelationScalarField::new(relation_name, "cheeksHeight"),
            cheeksWidth: RelationScalarField::new(relation_name, "cheeksWidth"),
            cheekSize: RelationScalarField::new(relation_name, "cheekSize"),
            neckSize: RelationScalarField::new(relation_name, "neckSize"),
            beardOpacity: RelationScalarField::new(relation_name, "beardOpacity"),
            blemishesOpacity: RelationScalarField::new(relation_name, "blemishesOpacity"),
            playerId: RelationScalarField::new(relation_name, "playerId"),
        })
    }
}

#[derive(Default)]
pub struct CharacterInclude {}

#[derive(Default)]
pub struct CharacterRelations {}

impl Projection<Character> for Character {
    fn columns() -> &'static [&'static str] {
        &[
            "id",
            "father",
            "mother",
            "skinFather",
            "skinMother",
            "eyebrowsColor",
            "lipstick",
            "hair",
            "hairColor",
            "bodyHair",
            "bodyHairColor",
            "beard",
            "beardColor",
            "blush",
            "makeup",
            "complexion",
            "sunDamage",
            "fleckles",
            "ageing",
            "blemishes",
            "bodyBlemishes",
            "eyeColor",
            "lips",
            "shapeMix",
            "skinMix",
            "eyeOpening",
            "eyebrows",
            "eyebrowsOpacity",
            "eyebrowHeight",
            "eyebrowDepth",
            "noseWidth",
            "noseHeight",
            "noseLength",
            "noseBridge",
            "noseTip",
            "noseCurvature",
            "jawWidth",
            "jawHeight",
            "chinLength",
            "chinPosition",
            "chinWidth",
            "chinShape",
            "cheeksHeight",
            "cheeksWidth",
            "cheekSize",
            "neckSize",
            "beardOpacity",
            "blemishesOpacity",
            "playerId",
        ]
    }
}

impl InsertModel for Character {
    fn insert_columns() -> &'static [&'static str] {
        &[
            "id",
            "father",
            "mother",
            "skinFather",
            "skinMother",
            "eyebrowsColor",
            "lipstick",
            "hair",
            "hairColor",
            "bodyHair",
            "bodyHairColor",
            "beard",
            "beardColor",
            "blush",
            "makeup",
            "complexion",
            "sunDamage",
            "fleckles",
            "ageing",
            "blemishes",
            "bodyBlemishes",
            "eyeColor",
            "lips",
            "shapeMix",
            "skinMix",
            "eyeOpening",
            "eyebrows",
            "eyebrowsOpacity",
            "eyebrowHeight",
            "eyebrowDepth",
            "noseWidth",
            "noseHeight",
            "noseLength",
            "noseBridge",
            "noseTip",
            "noseCurvature",
            "jawWidth",
            "jawHeight",
            "chinLength",
            "chinPosition",
            "chinWidth",
            "chinShape",
            "cheeksHeight",
            "cheeksWidth",
            "cheekSize",
            "neckSize",
            "beardOpacity",
            "blemishesOpacity",
            "playerId",
        ]
    }

    fn into_insert_row(self) -> Vec<dinoco::DinocoValue> {
        vec![
            self.id.into_dinoco_value(),
            self.father.into_dinoco_value(),
            self.mother.into_dinoco_value(),
            self.skinFather.into_dinoco_value(),
            self.skinMother.into_dinoco_value(),
            self.eyebrowsColor.into_dinoco_value(),
            self.lipstick.into_dinoco_value(),
            self.hair.into_dinoco_value(),
            self.hairColor.into_dinoco_value(),
            self.bodyHair.into_dinoco_value(),
            self.bodyHairColor.into_dinoco_value(),
            self.beard.into_dinoco_value(),
            self.beardColor.into_dinoco_value(),
            self.blush.into_dinoco_value(),
            self.makeup.into_dinoco_value(),
            self.complexion.into_dinoco_value(),
            self.sunDamage.into_dinoco_value(),
            self.fleckles.into_dinoco_value(),
            self.ageing.into_dinoco_value(),
            self.blemishes.into_dinoco_value(),
            self.bodyBlemishes.into_dinoco_value(),
            self.eyeColor.into_dinoco_value(),
            self.lips.into_dinoco_value(),
            self.shapeMix.into_dinoco_value(),
            self.skinMix.into_dinoco_value(),
            self.eyeOpening.into_dinoco_value(),
            self.eyebrows.into_dinoco_value(),
            self.eyebrowsOpacity.into_dinoco_value(),
            self.eyebrowHeight.into_dinoco_value(),
            self.eyebrowDepth.into_dinoco_value(),
            self.noseWidth.into_dinoco_value(),
            self.noseHeight.into_dinoco_value(),
            self.noseLength.into_dinoco_value(),
            self.noseBridge.into_dinoco_value(),
            self.noseTip.into_dinoco_value(),
            self.noseCurvature.into_dinoco_value(),
            self.jawWidth.into_dinoco_value(),
            self.jawHeight.into_dinoco_value(),
            self.chinLength.into_dinoco_value(),
            self.chinPosition.into_dinoco_value(),
            self.chinWidth.into_dinoco_value(),
            self.chinShape.into_dinoco_value(),
            self.cheeksHeight.into_dinoco_value(),
            self.cheeksWidth.into_dinoco_value(),
            self.cheekSize.into_dinoco_value(),
            self.neckSize.into_dinoco_value(),
            self.beardOpacity.into_dinoco_value(),
            self.blemishesOpacity.into_dinoco_value(),
            self.playerId.into_dinoco_value(),
        ]
    }

    fn insert_identity_conditions(&self) -> Vec<dinoco::Expression> {
        vec![
            dinoco::Expression::Column("id".to_string()).eq(self.id.clone().into_dinoco_value()),
        ]
    }

    fn validate_insert(&self) -> dinoco::DinocoResult<()> {
        Ok(())
    }
}

impl UpdateModel for Character {
    fn update_columns() -> &'static [&'static str] {
        &[
            "father",
            "mother",
            "skinFather",
            "skinMother",
            "eyebrowsColor",
            "lipstick",
            "hair",
            "hairColor",
            "bodyHair",
            "bodyHairColor",
            "beard",
            "beardColor",
            "blush",
            "makeup",
            "complexion",
            "sunDamage",
            "fleckles",
            "ageing",
            "blemishes",
            "bodyBlemishes",
            "eyeColor",
            "lips",
            "shapeMix",
            "skinMix",
            "eyeOpening",
            "eyebrows",
            "eyebrowsOpacity",
            "eyebrowHeight",
            "eyebrowDepth",
            "noseWidth",
            "noseHeight",
            "noseLength",
            "noseBridge",
            "noseTip",
            "noseCurvature",
            "jawWidth",
            "jawHeight",
            "chinLength",
            "chinPosition",
            "chinWidth",
            "chinShape",
            "cheeksHeight",
            "cheeksWidth",
            "cheekSize",
            "neckSize",
            "beardOpacity",
            "blemishesOpacity",
            "playerId",
        ]
    }

    fn into_update_row(self) -> Vec<dinoco::DinocoValue> {
        vec![
            self.father.into_dinoco_value(),
            self.mother.into_dinoco_value(),
            self.skinFather.into_dinoco_value(),
            self.skinMother.into_dinoco_value(),
            self.eyebrowsColor.into_dinoco_value(),
            self.lipstick.into_dinoco_value(),
            self.hair.into_dinoco_value(),
            self.hairColor.into_dinoco_value(),
            self.bodyHair.into_dinoco_value(),
            self.bodyHairColor.into_dinoco_value(),
            self.beard.into_dinoco_value(),
            self.beardColor.into_dinoco_value(),
            self.blush.into_dinoco_value(),
            self.makeup.into_dinoco_value(),
            self.complexion.into_dinoco_value(),
            self.sunDamage.into_dinoco_value(),
            self.fleckles.into_dinoco_value(),
            self.ageing.into_dinoco_value(),
            self.blemishes.into_dinoco_value(),
            self.bodyBlemishes.into_dinoco_value(),
            self.eyeColor.into_dinoco_value(),
            self.lips.into_dinoco_value(),
            self.shapeMix.into_dinoco_value(),
            self.skinMix.into_dinoco_value(),
            self.eyeOpening.into_dinoco_value(),
            self.eyebrows.into_dinoco_value(),
            self.eyebrowsOpacity.into_dinoco_value(),
            self.eyebrowHeight.into_dinoco_value(),
            self.eyebrowDepth.into_dinoco_value(),
            self.noseWidth.into_dinoco_value(),
            self.noseHeight.into_dinoco_value(),
            self.noseLength.into_dinoco_value(),
            self.noseBridge.into_dinoco_value(),
            self.noseTip.into_dinoco_value(),
            self.noseCurvature.into_dinoco_value(),
            self.jawWidth.into_dinoco_value(),
            self.jawHeight.into_dinoco_value(),
            self.chinLength.into_dinoco_value(),
            self.chinPosition.into_dinoco_value(),
            self.chinWidth.into_dinoco_value(),
            self.chinShape.into_dinoco_value(),
            self.cheeksHeight.into_dinoco_value(),
            self.cheeksWidth.into_dinoco_value(),
            self.cheekSize.into_dinoco_value(),
            self.neckSize.into_dinoco_value(),
            self.beardOpacity.into_dinoco_value(),
            self.blemishesOpacity.into_dinoco_value(),
            self.playerId.into_dinoco_value(),
        ]
    }

    fn update_identity_conditions(&self) -> Vec<dinoco::Expression> {
        vec![
            dinoco::Expression::Column("id".to_string()).eq(self.id.clone().into_dinoco_value()),
        ]
    }

    fn validate_update(&self) -> dinoco::DinocoResult<()> {
        Ok(())
    }
}

impl Default for CharacterWhere {
    fn default() -> Self {
        Self {
            id: ScalarField::new("id"),
            father: ScalarField::new("father"),
            mother: ScalarField::new("mother"),
            skinFather: ScalarField::new("skinFather"),
            skinMother: ScalarField::new("skinMother"),
            eyebrowsColor: ScalarField::new("eyebrowsColor"),
            lipstick: ScalarField::new("lipstick"),
            hair: ScalarField::new("hair"),
            hairColor: ScalarField::new("hairColor"),
            bodyHair: ScalarField::new("bodyHair"),
            bodyHairColor: ScalarField::new("bodyHairColor"),
            beard: ScalarField::new("beard"),
            beardColor: ScalarField::new("beardColor"),
            blush: ScalarField::new("blush"),
            makeup: ScalarField::new("makeup"),
            complexion: ScalarField::new("complexion"),
            sunDamage: ScalarField::new("sunDamage"),
            fleckles: ScalarField::new("fleckles"),
            ageing: ScalarField::new("ageing"),
            blemishes: ScalarField::new("blemishes"),
            bodyBlemishes: ScalarField::new("bodyBlemishes"),
            eyeColor: ScalarField::new("eyeColor"),
            lips: ScalarField::new("lips"),
            shapeMix: ScalarField::new("shapeMix"),
            skinMix: ScalarField::new("skinMix"),
            eyeOpening: ScalarField::new("eyeOpening"),
            eyebrows: ScalarField::new("eyebrows"),
            eyebrowsOpacity: ScalarField::new("eyebrowsOpacity"),
            eyebrowHeight: ScalarField::new("eyebrowHeight"),
            eyebrowDepth: ScalarField::new("eyebrowDepth"),
            noseWidth: ScalarField::new("noseWidth"),
            noseHeight: ScalarField::new("noseHeight"),
            noseLength: ScalarField::new("noseLength"),
            noseBridge: ScalarField::new("noseBridge"),
            noseTip: ScalarField::new("noseTip"),
            noseCurvature: ScalarField::new("noseCurvature"),
            jawWidth: ScalarField::new("jawWidth"),
            jawHeight: ScalarField::new("jawHeight"),
            chinLength: ScalarField::new("chinLength"),
            chinPosition: ScalarField::new("chinPosition"),
            chinWidth: ScalarField::new("chinWidth"),
            chinShape: ScalarField::new("chinShape"),
            cheeksHeight: ScalarField::new("cheeksHeight"),
            cheeksWidth: ScalarField::new("cheeksWidth"),
            cheekSize: ScalarField::new("cheekSize"),
            neckSize: ScalarField::new("neckSize"),
            beardOpacity: ScalarField::new("beardOpacity"),
            blemishesOpacity: ScalarField::new("blemishesOpacity"),
            playerId: ScalarField::new("playerId"),
        }
    }
}

impl Default for CharacterUpdate {
    fn default() -> Self {
        Self {
            father: UpdateField::new("father"),
            mother: UpdateField::new("mother"),
            skinFather: UpdateField::new("skinFather"),
            skinMother: UpdateField::new("skinMother"),
            eyebrowsColor: UpdateField::new("eyebrowsColor"),
            lipstick: UpdateField::new("lipstick"),
            hair: UpdateField::new("hair"),
            hairColor: UpdateField::new("hairColor"),
            bodyHair: UpdateField::new("bodyHair"),
            bodyHairColor: UpdateField::new("bodyHairColor"),
            beard: UpdateField::new("beard"),
            beardColor: UpdateField::new("beardColor"),
            blush: UpdateField::new("blush"),
            makeup: UpdateField::new("makeup"),
            complexion: UpdateField::new("complexion"),
            sunDamage: UpdateField::new("sunDamage"),
            fleckles: UpdateField::new("fleckles"),
            ageing: UpdateField::new("ageing"),
            blemishes: UpdateField::new("blemishes"),
            bodyBlemishes: UpdateField::new("bodyBlemishes"),
            eyeColor: UpdateField::new("eyeColor"),
            lips: UpdateField::new("lips"),
            shapeMix: UpdateField::new("shapeMix"),
            skinMix: UpdateField::new("skinMix"),
            eyeOpening: UpdateField::new("eyeOpening"),
            eyebrows: UpdateField::new("eyebrows"),
            eyebrowsOpacity: UpdateField::new("eyebrowsOpacity"),
            eyebrowHeight: UpdateField::new("eyebrowHeight"),
            eyebrowDepth: UpdateField::new("eyebrowDepth"),
            noseWidth: UpdateField::new("noseWidth"),
            noseHeight: UpdateField::new("noseHeight"),
            noseLength: UpdateField::new("noseLength"),
            noseBridge: UpdateField::new("noseBridge"),
            noseTip: UpdateField::new("noseTip"),
            noseCurvature: UpdateField::new("noseCurvature"),
            jawWidth: UpdateField::new("jawWidth"),
            jawHeight: UpdateField::new("jawHeight"),
            chinLength: UpdateField::new("chinLength"),
            chinPosition: UpdateField::new("chinPosition"),
            chinWidth: UpdateField::new("chinWidth"),
            chinShape: UpdateField::new("chinShape"),
            cheeksHeight: UpdateField::new("cheeksHeight"),
            cheeksWidth: UpdateField::new("cheeksWidth"),
            cheekSize: UpdateField::new("cheekSize"),
            neckSize: UpdateField::new("neckSize"),
            beardOpacity: UpdateField::new("beardOpacity"),
            blemishesOpacity: UpdateField::new("blemishesOpacity"),
            playerId: UpdateField::new("playerId"),
        }
    }
}

impl CharacterInclude {
    pub fn player(&self) -> RelationField<super::player::Player> {
        RelationField::new("player")
    }
}

impl CharacterRelations {
    pub fn player(&self) -> RelationMutationWhere<super::player::PlayerRelationWhere> {
        super::player::PlayerRelationWhere::new("player")
    }
}

impl Character {
    pub fn __dinoco_load_player<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Option<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::player::Player>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: Option<C>,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::player::Player>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    let relation_offset = C::columns().len();
                    let item = if row.get_optional::<dinoco::Uuid>(relation_offset)?.is_some() {
                        Some(C::from_row(row)?)
                    } else {
                        None
                    };

                    Ok(Self {
                        item,
                        relation_key: row.get(relation_offset + 1)?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let mut statement = dinoco::qualify_select_statement(
                include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("Player").select(C::columns())),
                "Player",
            );
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns()
                    .iter()
                    .map(|column| format!("{}.{}", "Player", column))
                    .collect::<Vec<_>>();
            }

            select_columns.push(format!("{}.{}", "Player", "id"));
            select_columns.push(format!("{}.{}", "Character", "playerId"));
            statement.select = select_columns;
            statement.conditions.push(
                dinoco::Expression::Column(format!("{}.{}", "Character", "playerId"))
                    .in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()),
            );
            statement.from = format!(
                "{} LEFT JOIN {} ON {}.{} = {}.{}",
                "Character",
                "Player",
                "Character",
                "playerId",
                "Player",
                "id",
            );

            let adapter = client.read_adapter(matches!(read_mode, dinoco::ReadMode::Primary));
            let partition_column = format!("{}.{}", "Character", "playerId");
            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, &partition_column, "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let mut child_pairs = Vec::new();

            for row in child_rows {
                if let Some(item) = row.item {
                    child_pairs.push((row.relation_key, item));
                }
            }

            let relation_keys = child_pairs.iter().map(|(relation_key, _)| relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_pairs.into_iter().map(|(_, item)| item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, C> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.insert(relation_key, child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key));
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Character {
    pub fn __dinoco_load_player_by_primary_key<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Option<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::player::Player>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: Option<C>,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::player::Player>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    let relation_offset = C::columns().len();
                    let item = if row.get_optional::<dinoco::Uuid>(relation_offset)?.is_some() {
                        Some(C::from_row(row)?)
                    } else {
                        None
                    };

                    Ok(Self {
                        item,
                        relation_key: row.get(relation_offset + 1)?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let mut statement = dinoco::qualify_select_statement(
                include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("Player").select(C::columns())),
                "Player",
            );
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns()
                    .iter()
                    .map(|column| format!("{}.{}", "Player", column))
                    .collect::<Vec<_>>();
            }

            select_columns.push(format!("{}.{}", "Player", "id"));
            select_columns.push(format!("{}.{}", "Character", "id"));
            statement.select = select_columns;
            statement.conditions.push(
                dinoco::Expression::Column(format!("{}.{}", "Character", "id"))
                    .in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()),
            );
            statement.from = format!(
                "{} LEFT JOIN {} ON {}.{} = {}.{}",
                "Character",
                "Player",
                "Character",
                "playerId",
                "Player",
                "id",
            );

            let adapter = client.read_adapter(matches!(read_mode, dinoco::ReadMode::Primary));
            let partition_column = format!("{}.{}", "Character", "id");
            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, &partition_column, "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let mut child_pairs = Vec::new();

            for row in child_rows {
                if let Some(item) = row.item {
                    child_pairs.push((row.relation_key, item));
                }
            }

            let relation_keys = child_pairs.iter().map(|(relation_key, _)| relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_pairs.into_iter().map(|(_, item)| item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, C> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.insert(relation_key, child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key));
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Character {
    pub fn __dinoco_count_player<'a, P, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        count: &'a dinoco::CountNode,
        client: &'a dinoco::DinocoClient<A>,
        _read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut usize + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            #[derive(Debug, Clone, dinoco::Rowable)]
            struct DinocoRelationCountRow {
                id: dinoco::Uuid,
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let adapter = client.read_adapter(false);
            let mut statement = count.statement.clone().unwrap_or_else(|| {
                dinoco::SelectStatement::new().from("Player").select(&["id"])
            });
            statement.select = vec!["id".to_string()];
            statement.conditions.push(dinoco::Expression::Column("id".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let rows = if statement.limit.is_some() || statement.skip.is_some() {
                let (sql, params) = dinoco::QueryBuilder::build_partitioned_select(
                    adapter.dialect(),
                    &statement,
                    "id",
                    "__dinoco_row_num",
                );
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            } else {
                let (sql, params) = dinoco::QueryBuilder::build_select(adapter.dialect(), &statement);
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            };

            let mut grouped: HashMap<dinoco::Uuid, usize> = HashMap::new();

            for row in rows {
                *grouped.entry(row.id).or_default() += 1;
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or(0);
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

#[derive(Debug, Clone, dinoco::serde::Serialize, dinoco::serde::Deserialize)]
#[serde(crate = "dinoco::serde")]
pub enum CharacterConnection {
    Player(dinoco::Uuid),
}

impl dinoco::InsertConnectionPayload<Character> for CharacterConnection {
    fn connection_updates(&self, parent: &Character) -> Vec<dinoco::ConnectionUpdatePlan> {
        match self {
            Self::Player(value) => vec![dinoco::ConnectionUpdatePlan {
                table_name: "Player",
                columns: &["id"],
                row: vec![parent.playerId.clone().into_dinoco_value()],
                conditions: vec![
                    dinoco::Expression::Column("id".to_string()).eq(value.clone().into_dinoco_value()),
                ],
            }],
        }
    }

    fn relation_links(&self, parent: &Character) -> Vec<dinoco::RelationLinkPlan> {
        match self {
            Self::Player(_) => Vec::new(),
        }
    }
}

impl Model for Character {
    type Include = CharacterInclude;
    type Where = CharacterWhere;

    fn table_name() -> &'static str {
        "Character"
    }
}

impl RelationMutationModel for Character {
    type Relations = CharacterRelations;

    fn relation_write_plan(target: dinoco::RelationMutationTarget) -> Option<RelationWritePlan> {
        match target.relation_name {
            _ => None,
        }
    }
}

impl FindAndUpdateModel for Character {
    type Update = CharacterUpdate;

    fn primary_key_columns() -> &'static [&'static str] {
        &[
            "id",
        ]
    }
}
