// ==============================================================
// =================== DINOCO MANAGED FILE =======================
// ==============================================================
// This file is generated and managed by Dinoco.
// Do not edit this file manually.
// Any manual changes will be overwritten the next time Dinoco runs.
// ==============================================================

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
#![allow(unused_variables)]

use dinoco::{AdapterDialect, FindAndUpdateModel, InsertModel, IntoDinocoValue, Model, Projection, RelationField, RelationMutationModel, RelationMutationWhere, RelationScalarField, RelationWritePlan, Rowable, ScalarField, UpdateField, UpdateModel};
use super::{player::Player};

#[derive(Debug, Clone, dinoco::serde::Serialize, dinoco::serde::Deserialize, Rowable)]
#[serde(crate = "dinoco::serde")]
pub struct Subscription {
    pub id: dinoco::Uuid,
    pub color: String,
    pub endAt: dinoco::DateTimeUtc<dinoco::Utc>,
    pub startedAt: dinoco::DateTimeUtc<dinoco::Utc>,
    pub playerId: Option<dinoco::Uuid>,
}

impl Subscription {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Default for Subscription {
    fn default() -> Self {
        Self {
            id: dinoco::Uuid::new(),
            color: "#ffd900".to_string(),
            endAt: dinoco::Utc::now(),
            startedAt: dinoco::Utc::now(),
            playerId: None,
        }
    }
}

pub struct SubscriptionWhere {
    pub id: ScalarField<String>,
    pub color: ScalarField<String>,
    pub endAt: ScalarField<dinoco::DateTimeUtc<dinoco::Utc>>,
    pub startedAt: ScalarField<dinoco::DateTimeUtc<dinoco::Utc>>,
    pub playerId: ScalarField<String>,
}

pub struct SubscriptionUpdate {
    pub color: UpdateField<String>,
    pub endAt: UpdateField<dinoco::DateTimeUtc<dinoco::Utc>>,
    pub startedAt: UpdateField<dinoco::DateTimeUtc<dinoco::Utc>>,
    pub playerId: UpdateField<String>,
}

pub struct SubscriptionRelationWhere {
    pub id: RelationScalarField<String>,
    pub color: RelationScalarField<String>,
    pub endAt: RelationScalarField<dinoco::DateTimeUtc<dinoco::Utc>>,
    pub startedAt: RelationScalarField<dinoco::DateTimeUtc<dinoco::Utc>>,
    pub playerId: RelationScalarField<String>,
}

impl SubscriptionRelationWhere {
    pub fn new(relation_name: &'static str) -> RelationMutationWhere<Self> {
        RelationMutationWhere::new(Self {
            id: RelationScalarField::new(relation_name, "id"),
            color: RelationScalarField::new(relation_name, "color"),
            endAt: RelationScalarField::new(relation_name, "endAt"),
            startedAt: RelationScalarField::new(relation_name, "startedAt"),
            playerId: RelationScalarField::new(relation_name, "playerId"),
        })
    }
}

#[derive(Default)]
pub struct SubscriptionInclude {}

#[derive(Default)]
pub struct SubscriptionRelations {}

impl Projection<Subscription> for Subscription {
    fn columns() -> &'static [&'static str] {
        &[
            "id",
            "color",
            "endAt",
            "startedAt",
            "playerId",
        ]
    }
}

impl InsertModel for Subscription {
    fn insert_columns() -> &'static [&'static str] {
        &[
            "id",
            "color",
            "endAt",
            "startedAt",
            "playerId",
        ]
    }

    fn into_insert_row(self) -> Vec<dinoco::DinocoValue> {
        vec![
            self.id.into_dinoco_value(),
            self.color.into_dinoco_value(),
            self.endAt.into_dinoco_value(),
            self.startedAt.into_dinoco_value(),
            self.playerId.into_dinoco_value(),
        ]
    }

    fn insert_identity_conditions(&self) -> Vec<dinoco::Expression> {
        vec![
            dinoco::Expression::Column("id".to_string()).eq(self.id.clone().into_dinoco_value()),
        ]
    }

    fn validate_insert(&self) -> dinoco::DinocoResult<()> {
        Ok(())
    }
}

impl UpdateModel for Subscription {
    fn update_columns() -> &'static [&'static str] {
        &[
            "color",
            "endAt",
            "startedAt",
            "playerId",
        ]
    }

    fn into_update_row(self) -> Vec<dinoco::DinocoValue> {
        vec![
            self.color.into_dinoco_value(),
            self.endAt.into_dinoco_value(),
            self.startedAt.into_dinoco_value(),
            self.playerId.into_dinoco_value(),
        ]
    }

    fn update_identity_conditions(&self) -> Vec<dinoco::Expression> {
        vec![
            dinoco::Expression::Column("id".to_string()).eq(self.id.clone().into_dinoco_value()),
        ]
    }

    fn validate_update(&self) -> dinoco::DinocoResult<()> {
        Ok(())
    }
}

impl Default for SubscriptionWhere {
    fn default() -> Self {
        Self {
            id: ScalarField::new("id"),
            color: ScalarField::new("color"),
            endAt: ScalarField::new("endAt"),
            startedAt: ScalarField::new("startedAt"),
            playerId: ScalarField::new("playerId"),
        }
    }
}

impl Default for SubscriptionUpdate {
    fn default() -> Self {
        Self {
            color: UpdateField::new("color"),
            endAt: UpdateField::new("endAt"),
            startedAt: UpdateField::new("startedAt"),
            playerId: UpdateField::new("playerId"),
        }
    }
}

impl SubscriptionInclude {
    pub fn player(&self) -> RelationField<super::player::Player> {
        RelationField::new("player")
    }
}

impl SubscriptionRelations {
    pub fn player(&self) -> RelationMutationWhere<super::player::PlayerRelationWhere> {
        super::player::PlayerRelationWhere::new("player")
    }
}

impl Subscription {
    pub fn __dinoco_load_player<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Option<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::player::Player>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: Option<C>,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::player::Player>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    let relation_offset = C::columns().len();
                    let item = if row.get_optional::<dinoco::Uuid>(relation_offset)?.is_some() {
                        Some(C::from_row(row)?)
                    } else {
                        None
                    };

                    Ok(Self {
                        item,
                        relation_key: row.get(relation_offset + 1)?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let mut statement = dinoco::qualify_select_statement(
                include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("Player").select(C::columns())),
                "Player",
            );
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns()
                    .iter()
                    .map(|column| format!("{}.{}", "Player", column))
                    .collect::<Vec<_>>();
            }

            select_columns.push(format!("{}.{}", "Player", "id"));
            select_columns.push(format!("{}.{}", "Subscription", "playerId"));
            statement.select = select_columns;
            statement.conditions.push(
                dinoco::Expression::Column(format!("{}.{}", "Subscription", "playerId"))
                    .in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()),
            );
            statement.from = format!(
                "{} LEFT JOIN {} ON {}.{} = {}.{}",
                "Subscription",
                "Player",
                "Subscription",
                "playerId",
                "Player",
                "id",
            );

            let adapter = client.read_adapter(matches!(read_mode, dinoco::ReadMode::Primary));
            let partition_column = format!("{}.{}", "Subscription", "playerId");
            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, &partition_column, "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let mut child_pairs = Vec::new();

            for row in child_rows {
                if let Some(item) = row.item {
                    child_pairs.push((row.relation_key, item));
                }
            }

            let relation_keys = child_pairs.iter().map(|(relation_key, _)| relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_pairs.into_iter().map(|(_, item)| item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, C> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.insert(relation_key, child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key));
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Subscription {
    pub fn __dinoco_load_player_by_primary_key<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Option<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::player::Player>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: Option<C>,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::player::Player>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    let relation_offset = C::columns().len();
                    let item = if row.get_optional::<dinoco::Uuid>(relation_offset)?.is_some() {
                        Some(C::from_row(row)?)
                    } else {
                        None
                    };

                    Ok(Self {
                        item,
                        relation_key: row.get(relation_offset + 1)?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let mut statement = dinoco::qualify_select_statement(
                include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("Player").select(C::columns())),
                "Player",
            );
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns()
                    .iter()
                    .map(|column| format!("{}.{}", "Player", column))
                    .collect::<Vec<_>>();
            }

            select_columns.push(format!("{}.{}", "Player", "id"));
            select_columns.push(format!("{}.{}", "Subscription", "id"));
            statement.select = select_columns;
            statement.conditions.push(
                dinoco::Expression::Column(format!("{}.{}", "Subscription", "id"))
                    .in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()),
            );
            statement.from = format!(
                "{} LEFT JOIN {} ON {}.{} = {}.{}",
                "Subscription",
                "Player",
                "Subscription",
                "playerId",
                "Player",
                "id",
            );

            let adapter = client.read_adapter(matches!(read_mode, dinoco::ReadMode::Primary));
            let partition_column = format!("{}.{}", "Subscription", "id");
            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, &partition_column, "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let mut child_pairs = Vec::new();

            for row in child_rows {
                if let Some(item) = row.item {
                    child_pairs.push((row.relation_key, item));
                }
            }

            let relation_keys = child_pairs.iter().map(|(relation_key, _)| relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_pairs.into_iter().map(|(_, item)| item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, C> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.insert(relation_key, child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key));
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Subscription {
    pub fn __dinoco_count_player<'a, P, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        count: &'a dinoco::CountNode,
        client: &'a dinoco::DinocoClient<A>,
        _read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut usize + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            #[derive(Debug, Clone, dinoco::Rowable)]
            struct DinocoRelationCountRow {
                id: dinoco::Uuid,
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let adapter = client.read_adapter(false);
            let mut statement = count.statement.clone().unwrap_or_else(|| {
                dinoco::SelectStatement::new().from("Player").select(&["id"])
            });
            statement.select = vec!["id".to_string()];
            statement.conditions.push(dinoco::Expression::Column("id".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let rows = if statement.limit.is_some() || statement.skip.is_some() {
                let (sql, params) = dinoco::QueryBuilder::build_partitioned_select(
                    adapter.dialect(),
                    &statement,
                    "id",
                    "__dinoco_row_num",
                );
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            } else {
                let (sql, params) = dinoco::QueryBuilder::build_select(adapter.dialect(), &statement);
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            };

            let mut grouped: HashMap<dinoco::Uuid, usize> = HashMap::new();

            for row in rows {
                *grouped.entry(row.id).or_default() += 1;
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or(0);
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

#[derive(Debug, Clone, dinoco::serde::Serialize, dinoco::serde::Deserialize)]
#[serde(crate = "dinoco::serde")]
pub enum SubscriptionConnection {
    Player(dinoco::Uuid),
}

impl dinoco::InsertConnectionPayload<Subscription> for SubscriptionConnection {
    fn connection_updates(&self, parent: &Subscription) -> Vec<dinoco::ConnectionUpdatePlan> {
        match self {
            Self::Player(value) => vec![dinoco::ConnectionUpdatePlan {
                table_name: "Player",
                columns: &["id"],
                row: vec![parent.playerId.clone().into_dinoco_value()],
                conditions: vec![
                    dinoco::Expression::Column("id".to_string()).eq(value.clone().into_dinoco_value()),
                ],
            }],
        }
    }

    fn relation_links(&self, parent: &Subscription) -> Vec<dinoco::RelationLinkPlan> {
        match self {
            Self::Player(_) => Vec::new(),
        }
    }
}

impl Model for Subscription {
    type Include = SubscriptionInclude;
    type Where = SubscriptionWhere;

    fn table_name() -> &'static str {
        "Subscription"
    }
}

impl RelationMutationModel for Subscription {
    type Relations = SubscriptionRelations;

    fn relation_write_plan(target: dinoco::RelationMutationTarget) -> Option<RelationWritePlan> {
        match target.relation_name {
            _ => None,
        }
    }
}

impl FindAndUpdateModel for Subscription {
    type Update = SubscriptionUpdate;

    fn primary_key_columns() -> &'static [&'static str] {
        &[
            "id",
        ]
    }
}
