[package]
name = "dinoco_vscode"
version = "1.0.5"
edition = "2024"
license = "Apache-2.0"
description = "Language server components for Dinoco editor and VS Code integration."
repository = "https://github.com/dinoco-rs/dinoco"

[dependencies]
dinoco_compiler = { path = "../dinoco_compiler", version = "1.0.5" }
dinoco_formatter = { path = "../dinoco_formatter", version = "1.0.5" }
tokio = { version = "1.50", features = ["io-std", "macros", "rt-multi-thread", "sync"] }
tower-lsp = "0.20"
