import { useMemo } from 'react';

import { type DocsLocale, useDocs } from './useDocs';

const messages = {
	'pt-br': {
		description: 'Documentação oficial',
		donate: 'Apoiar',
		github: 'GitHub',
		localeLabel: 'Idioma',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: {
			docs: 'Docs',
			examples: 'Exemplos',
			guides: 'Guias',
			reference: 'Referência',
		},
		themeDark: 'Modo escuro',
		themeLight: 'Modo claro',
		versionLabel: 'Versão',
		constructionBadge: 'Em construção',
		constructionTitle: 'Conteúdo em desenvolvimento',
		constructionDescription: 'Esta seção da documentação ainda está em desenvolvimento. Volte em breve para conferir as novidades!',
		inPageLabel: 'Nesta página',
	},
	'en-us': {
		description: 'Official documentation',
		donate: 'Support',
		github: 'GitHub',
		localeLabel: 'Language',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: 'Examples', guides: 'Guides', reference: 'Reference' },
		themeDark: 'Dark mode',
		themeLight: 'Light mode',
		versionLabel: 'Version',
		constructionBadge: 'In progress',
		constructionTitle: 'Content in progress',
		constructionDescription: 'This documentation section is still in progress. Check back soon for updates.',
		inPageLabel: 'On this page',
	},
	'ru-ru': {
		description: 'Официальная документация',
		donate: 'Поддержать',
		github: 'GitHub',
		localeLabel: 'Язык',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Документация', examples: 'Примеры', guides: 'Руководства', reference: 'Справка' },
		themeDark: 'Тёмная тема',
		themeLight: 'Светлая тема',
		versionLabel: 'Версия',
		constructionBadge: 'В разработке',
		constructionTitle: 'Контент в разработке',
		constructionDescription: 'Этот раздел документации ещё находится в разработке. Скоро здесь появятся обновления.',
		inPageLabel: 'На этой странице',
	},
	'ja-jp': {
		description: '公式ドキュメント',
		donate: '支援する',
		github: 'GitHub',
		localeLabel: '言語',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: '例', guides: 'ガイド', reference: 'リファレンス' },
		themeDark: 'ダークモード',
		themeLight: 'ライトモード',
		versionLabel: 'バージョン',
		constructionBadge: '開発中',
		constructionTitle: 'コンテンツは準備中です',
		constructionDescription: 'このドキュメントセクションは現在作成中です。更新をお待ちください。',
		inPageLabel: 'このページ',
	},
	'ko-kr': {
		description: '공식 문서',
		donate: '후원하기',
		github: 'GitHub',
		localeLabel: '언어',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: '문서', examples: '예제', guides: '가이드', reference: '레퍼런스' },
		themeDark: '다크 모드',
		themeLight: '라이트 모드',
		versionLabel: '버전',
		constructionBadge: '작성 중',
		constructionTitle: '콘텐츠 작성 중',
		constructionDescription: '이 문서 섹션은 아직 작성 중입니다. 곧 다시 확인해 주세요.',
		inPageLabel: '이 페이지',
	},
	'de-de': {
		description: 'Offizielle Dokumentation',
		donate: 'Unterstützen',
		github: 'GitHub',
		localeLabel: 'Sprache',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: 'Beispiele', guides: 'Leitfäden', reference: 'Referenz' },
		themeDark: 'Dunkler Modus',
		themeLight: 'Heller Modus',
		versionLabel: 'Version',
		constructionBadge: 'In Arbeit',
		constructionTitle: 'Inhalt in Arbeit',
		constructionDescription: 'Dieser Abschnitt der Dokumentation ist noch in Arbeit. Schau bald wieder vorbei.',
		inPageLabel: 'Auf dieser Seite',
	},
	'it-it': {
		description: 'Documentazione ufficiale',
		donate: 'Supporta',
		github: 'GitHub',
		localeLabel: 'Lingua',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: 'Esempi', guides: 'Guide', reference: 'Riferimento' },
		themeDark: 'Tema scuro',
		themeLight: 'Tema chiaro',
		versionLabel: 'Versione',
		constructionBadge: 'In costruzione',
		constructionTitle: 'Contenuto in sviluppo',
		constructionDescription: 'Questa sezione della documentazione è ancora in sviluppo. Torna presto per gli aggiornamenti.',
		inPageLabel: 'In questa pagina',
	},
	'zh-cn': {
		description: '官方文档',
		donate: '支持',
		github: 'GitHub',
		localeLabel: '语言',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: '文档', examples: '示例', guides: '指南', reference: '参考' },
		themeDark: '深色模式',
		themeLight: '浅色模式',
		versionLabel: '版本',
		constructionBadge: '开发中',
		constructionTitle: '内容开发中',
		constructionDescription: '此文档章节仍在开发中。请稍后回来查看更新。',
		inPageLabel: '本页内容',
	},
	'fr-fr': {
		description: 'Documentation officielle',
		donate: 'Soutenir',
		github: 'GitHub',
		localeLabel: 'Langue',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: 'Exemples', guides: 'Guides', reference: 'Référence' },
		themeDark: 'Mode sombre',
		themeLight: 'Mode clair',
		versionLabel: 'Version',
		constructionBadge: 'En cours',
		constructionTitle: 'Contenu en cours',
		constructionDescription: 'Cette section de la documentation est encore en cours de rédaction. Revenez bientôt.',
		inPageLabel: 'Sur cette page',
	},
} as const;

export function getIntlMessages(locale: DocsLocale) {
	return messages[locale];
}

export function useIntl() {
	const locale = useDocs(state => state.locale);

	return useMemo(() => getIntlMessages(locale), [locale]);
}
