import type { DocsLocale } from '../jsons/versions';

// const messages = {
// 	'pt-br': {
// 		description: 'Documentacao oficial',
// 		donate: 'Apoiar',
// 		github: 'GitHub',
// 		localeLabel: 'Idioma',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: {
// 			docs: 'Docs',
// 			examples: 'Exemplos',
// 			guides: 'Guias',
// 			reference: 'Referencia',
// 		},
// 		themeDark: 'Modo escuro',
// 		themeLight: 'Modo claro',
// 		versionLabel: 'Versao',

// 		versionOld: 'Você está consultando a documentação da versão antiga',
// 		versionNew: 'A versão mais recente é a',
// 		goto: 'Ir para',

// 		constructionBadge: 'Em construcao',
// 		constructionTitle: 'Conteudo em desenvolvimento',
// 		constructionDescription: 'Esta secao da documentacao ainda esta em desenvolvimento. Volte em breve para conferir as novidades!',
// 		inPageLabel: 'Nesta pagina',
// 	},
// 	'en-us': {
// 		description: 'Official documentation',
// 		donate: 'Support',
// 		github: 'GitHub',
// 		localeLabel: 'Language',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: { docs: 'Docs', examples: 'Examples', guides: 'Guides', reference: 'Reference' },
// 		themeDark: 'Dark mode',
// 		themeLight: 'Light mode',
// 		versionLabel: 'Version',
// 		constructionBadge: 'In progress',
// 		constructionTitle: 'Content in progress',
// 		constructionDescription: 'This documentation section is still in progress. Check back soon for updates.',
// 		inPageLabel: 'On this page',
// 	},
// 	'ru-ru': {
// 		description: 'Официальная документация',
// 		donate: 'Поддержать',
// 		github: 'GitHub',
// 		localeLabel: 'Язык',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: { docs: 'Документация', examples: 'Примеры', guides: 'Руководства', reference: 'Справка' },
// 		themeDark: 'Тёмная тема',
// 		themeLight: 'Светлая тема',
// 		versionLabel: 'Версия',
// 		constructionBadge: 'В разработке',
// 		constructionTitle: 'Контент в разработке',
// 		constructionDescription: 'Этот раздел документации ещё находится в разработке. Скоро здесь появятся обновления.',
// 		inPageLabel: 'На этой странице',
// 	},
// 	'ja-jp': {
// 		description: '公式ドキュメント',
// 		donate: '支援する',
// 		github: 'GitHub',
// 		localeLabel: '言語',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: { docs: 'Docs', examples: '例', guides: 'ガイド', reference: 'リファレンス' },
// 		themeDark: 'ダークモード',
// 		themeLight: 'ライトモード',
// 		versionLabel: 'バージョン',
// 		constructionBadge: '作成中',
// 		constructionTitle: 'コンテンツ作成中',
// 		constructionDescription: 'このドキュメントセクションはまだ作成中です。近日中に更新されます。',
// 		inPageLabel: 'このページ',
// 	},
// 	'ko-kr': {
// 		description: '공식 문서',
// 		donate: '후원하기',
// 		github: 'GitHub',
// 		localeLabel: '언어',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: { docs: '문서', examples: '예제', guides: '가이드', reference: '레퍼런스' },
// 		themeDark: '다크 모드',
// 		themeLight: '라이트 모드',
// 		versionLabel: '버전',
// 		constructionBadge: '작성 중',
// 		constructionTitle: '콘텐츠 작성 중',
// 		constructionDescription: '이 문서 섹션은 아직 작성 중입니다. 곧 다시 확인해 주세요.',
// 		inPageLabel: '이 페이지',
// 	},
// 	'de-de': {
// 		description: 'Offizielle Dokumentation',
// 		donate: 'Unterstuetzen',
// 		github: 'GitHub',
// 		localeLabel: 'Sprache',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: { docs: 'Docs', examples: 'Beispiele', guides: 'Leitfaeden', reference: 'Referenz' },
// 		themeDark: 'Dunkler Modus',
// 		themeLight: 'Heller Modus',
// 		versionLabel: 'Version',
// 		constructionBadge: 'In Arbeit',
// 		constructionTitle: 'Inhalt in Arbeit',
// 		constructionDescription: 'Dieser Abschnitt der Dokumentation ist noch in Arbeit. Schau bald wieder vorbei.',
// 		inPageLabel: 'Auf dieser Seite',
// 	},
// 	'it-it': {
// 		description: 'Documentazione ufficiale',
// 		donate: 'Supporta',
// 		github: 'GitHub',
// 		localeLabel: 'Lingua',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: { docs: 'Docs', examples: 'Esempi', guides: 'Guide', reference: 'Riferimento' },
// 		themeDark: 'Tema scuro',
// 		themeLight: 'Tema chiaro',
// 		versionLabel: 'Versione',
// 		constructionBadge: 'In costruzione',
// 		constructionTitle: 'Contenuto in sviluppo',
// 		constructionDescription: 'Questa sezione della documentazione e ancora in sviluppo. Torna presto per gli aggiornamenti.',
// 		inPageLabel: 'In questa pagina',
// 	},
// 	'zh-cn': {
// 		description: '官方文档',
// 		donate: '支持',
// 		github: 'GitHub',
// 		localeLabel: '语言',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: { docs: '文档', examples: '示例', guides: '指南', reference: '参考' },
// 		themeDark: '深色模式',
// 		themeLight: '浅色模式',
// 		versionLabel: '版本',
// 		constructionBadge: '开发中',
// 		constructionTitle: '内容开发中',
// 		constructionDescription: '此文档章节仍在开发中。请稍后回来查看更新。',
// 		inPageLabel: '本页内容',
// 	},
// 	'fr-fr': {
// 		description: 'Documentation officielle',
// 		donate: 'Soutenir',
// 		github: 'GitHub',
// 		localeLabel: 'Langue',
// 		locales: {
// 			'pt-br': 'pt-br',
// 			'en-us': 'en-us',
// 			'ru-ru': 'ru-ru',
// 			'ja-jp': 'ja-jp',
// 			'ko-kr': 'ko-kr',
// 			'de-de': 'de-de',
// 			'it-it': 'it-it',
// 			'zh-cn': 'zh-cn',
// 			'fr-fr': 'fr-fr',
// 		},
// 		nav: { docs: 'Docs', examples: 'Exemples', guides: 'Guides', reference: 'Reference' },
// 		themeDark: 'Mode sombre',
// 		themeLight: 'Mode clair',
// 		versionLabel: 'Version',
// 		constructionBadge: 'En cours',
// 		constructionTitle: 'Contenu en cours',
// 		constructionDescription: 'Cette section de la documentation est encore en cours de redaction. Revenez bientot.',
// 		inPageLabel: 'Sur cette page',
// 	},
// } as const;

const messages = {
	'pt-br': {
		description: 'Documentacao oficial',
		donate: 'Apoiar',
		github: 'GitHub',
		localeLabel: 'Idioma',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: {
			docs: 'Docs',
			examples: 'Exemplos',
			guides: 'Guias',
			reference: 'Referencia',
		},
		themeDark: 'Modo escuro',
		themeLight: 'Modo claro',
		versionLabel: 'Versao',
		versionOld: 'Você está consultando a documentação da versão antiga',
		versionNew: 'A versão mais recente é a',
		goto: 'Ir para',
		constructionBadge: 'Em construcao',
		constructionTitle: 'Conteudo em desenvolvimento',
		constructionDescription: 'Esta secao da documentacao ainda esta em desenvolvimento. Volte em breve para conferir as novidades!',
		inPageLabel: 'Nesta pagina',
	},
	'en-us': {
		description: 'Official documentation',
		donate: 'Support',
		github: 'GitHub',
		localeLabel: 'Language',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: 'Examples', guides: 'Guides', reference: 'Reference' },
		themeDark: 'Dark mode',
		themeLight: 'Light mode',
		versionLabel: 'Version',
		versionOld: 'You are viewing the documentation for an older version',
		versionNew: 'The latest version is',
		goto: 'Go to',
		constructionBadge: 'In progress',
		constructionTitle: 'Content in progress',
		constructionDescription: 'This documentation section is still in progress. Check back soon for updates.',
		inPageLabel: 'On this page',
	},
	'ru-ru': {
		description: 'Официальная документация',
		donate: 'Поддержать',
		github: 'GitHub',
		localeLabel: 'Язык',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Документация', examples: 'Примеры', guides: 'Руководства', reference: 'Справка' },
		themeDark: 'Тёмная тема',
		themeLight: 'Светлая тема',
		versionLabel: 'Версия',
		versionOld: 'Вы просматриваете документацию для старой версии',
		versionNew: 'Самая последняя версия -',
		goto: 'Перейти к',
		constructionBadge: 'В разработке',
		constructionTitle: 'Контент в разработке',
		constructionDescription: 'Этот раздел документации ещё находится в разработке. Скоро здесь появятся обновления.',
		inPageLabel: 'На этой странице',
	},
	'ja-jp': {
		description: '公式ドキュメント',
		donate: '支援する',
		github: 'GitHub',
		localeLabel: '言語',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: '例', guides: 'ガイド', reference: 'リファレンス' },
		themeDark: 'ダークモード',
		themeLight: 'ライトモード',
		versionLabel: 'バージョン',
		versionOld: '古いバージョンのドキュメントを表示しています',
		versionNew: '最新バージョンは',
		goto: '移動',
		constructionBadge: '作成中',
		constructionTitle: 'コンテンツ作成中',
		constructionDescription: 'このドキュメントセクションはまだ作成中です。近日中に更新されます。',
		inPageLabel: 'このページ',
	},
	'ko-kr': {
		description: '공식 문서',
		donate: '후원하기',
		github: 'GitHub',
		localeLabel: '언어',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: '문서', examples: '예제', guides: '가이드', reference: '레퍼런스' },
		themeDark: '다크 모드',
		themeLight: '라이트 모드',
		versionLabel: '버전',
		versionOld: '이전 버전의 문서를 보고 계십니다',
		versionNew: '최신 버전은',
		goto: '이동',
		constructionBadge: '작성 중',
		constructionTitle: '콘텐츠 작성 중',
		constructionDescription: '이 문서 섹션은 아직 작성 중입니다. 곧 다시 확인해 주세요.',
		inPageLabel: '이 페이지',
	},
	'de-de': {
		description: 'Offizielle Dokumentation',
		donate: 'Unterstuetzen',
		github: 'GitHub',
		localeLabel: 'Sprache',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: 'Beispiele', guides: 'Leitfaeden', reference: 'Referenz' },
		themeDark: 'Dunkler Modus',
		themeLight: 'Heller Modus',
		versionLabel: 'Version',
		versionOld: 'Sie lesen die Dokumentation einer älteren Version',
		versionNew: 'Die neueste Version ist',
		goto: 'Gehe zu',
		constructionBadge: 'In Arbeit',
		constructionTitle: 'Inhalt in Arbeit',
		constructionDescription: 'Dieser Abschnitt der Dokumentation ist noch in Arbeit. Schau bald wieder vorbei.',
		inPageLabel: 'Auf dieser Seite',
	},
	'it-it': {
		description: 'Documentazione ufficiale',
		donate: 'Supporta',
		github: 'GitHub',
		localeLabel: 'Lingua',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: 'Esempi', guides: 'Guide', reference: 'Riferimento' },
		themeDark: 'Tema scuro',
		themeLight: 'Tema chiaro',
		versionLabel: 'Versione',
		versionOld: 'Stai consultando la documentazione di una versione precedente',
		versionNew: 'La versione più recente è la',
		goto: 'Vai a',
		constructionBadge: 'In costruzione',
		constructionTitle: 'Contenuto in sviluppo',
		constructionDescription: 'Questa sezione della documentazione e ancora in sviluppo. Torna presto per gli aggiornamenti.',
		inPageLabel: 'In questa pagina',
	},
	'zh-cn': {
		description: '官方文档',
		donate: '支持',
		github: 'GitHub',
		localeLabel: '语言',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: '文档', examples: '示例', guides: '指南', reference: '参考' },
		themeDark: '深色模式',
		themeLight: '浅色模式',
		versionLabel: '版本',
		versionOld: '您正在查看旧版文档',
		versionNew: '最新版本是',
		goto: '前往',
		constructionBadge: '开发中',
		constructionTitle: '内容开发中',
		constructionDescription: '此文档章节仍在开发中。请稍后回来查看更新。',
		inPageLabel: '本页内容',
	},
	'fr-fr': {
		description: 'Documentation officielle',
		donate: 'Soutenir',
		github: 'GitHub',
		localeLabel: 'Langue',
		locales: {
			'pt-br': 'pt-br',
			'en-us': 'en-us',
			'ru-ru': 'ru-ru',
			'ja-jp': 'ja-jp',
			'ko-kr': 'ko-kr',
			'de-de': 'de-de',
			'it-it': 'it-it',
			'zh-cn': 'zh-cn',
			'fr-fr': 'fr-fr',
		},
		nav: { docs: 'Docs', examples: 'Exemples', guides: 'Guides', reference: 'Reference' },
		themeDark: 'Mode sombre',
		themeLight: 'Mode clair',
		versionLabel: 'Version',
		versionOld: "Vous consultez la documentation d'une ancienne version",
		versionNew: 'La dernière version est',
		goto: 'Aller à',
		constructionBadge: 'En cours',
		constructionTitle: 'Contenu en cours',
		constructionDescription: 'Cette section de la documentation est encore en cours de redaction. Revenez bientot.',
		inPageLabel: 'Sur cette page',
	},
} as const;

export function getIntlMessages(locale: DocsLocale) {
	return messages[locale];
}
