use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use dinoco_cli::db::CliDatabase;
use dinoco_engine::{DinocoAdapter, DinocoSqlCompiler, FindQuery, MySqlAdapter, PostgresAdapter};

const POSTGRES_ADMIN_URL: &str = "postgres://postgres:postgres@localhost:5432/postgres";
const MYSQL_ADMIN_URL: &str = "mysql://root:root@localhost:3306/mysql";
static NEXT_TEST_ID: AtomicU64 = AtomicU64::new(0);

#[derive(Clone, Copy)]
enum ServerDatabase {
    Postgres,
    Mysql,
}

#[tokio::test]
async fn postgres_migrations_preserve_data_repair_missing_tables_and_verify_checksums() -> anyhow::Result<()> {
    exercise_server_migrations(ServerDatabase::Postgres).await
}

#[tokio::test]
async fn mysql_migrations_preserve_data_repair_missing_tables_and_verify_checksums() -> anyhow::Result<()> {
    exercise_server_migrations(ServerDatabase::Mysql).await
}

#[tokio::test]
async fn postgres_generate_upgrades_legacy_pascal_case_tables_without_losing_rows() -> anyhow::Result<()> {
    let suffix = format!("{}_{}_{}", std::process::id(), monotonic(), NEXT_TEST_ID.fetch_add(1, Ordering::Relaxed));
    let database_name = format!("dinoco_pg_legacy_{suffix}");
    create_database(ServerDatabase::Postgres, &database_name).await?;
    let database_url = format!("postgres://postgres:postgres@localhost:5432/{database_name}");
    let project = temporary_project("pg-legacy", &suffix);

    let outcome = async {
        fs::create_dir_all(project.join("dinoco/migrations/20240101000000_legacy"))?;
        fs::write(
            project.join("dinoco/schema.dinoco"),
            r#"
config {
    database = "postgresql"
    database_url = env("DATABASE_URL")
}

model Account {
    id              Integer         @id @default(autoincrement())
    name            String
    audio_creations AudioCreation[]
}

model AudioCreation {
    id         Integer          @id @default(autoincrement())
    createdAt  DateTime         @default(now())
    variations AudioVariation[]
    account_id Integer?
    account    Account?         @relation(fields: [account_id], references: [id], onUpdate: Cascade, onDelete: Cascade)
}

model AudioVariation {
    id          Integer        @id @default(autoincrement())
    creation_id Integer?
    creation    AudioCreation? @relation(fields: [creation_id], references: [id], onUpdate: Cascade, onDelete: Cascade)
}
"#,
        )?;
        let legacy_account_sql = r#"CREATE TABLE "Account" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL
);"#;
        let legacy_audio_sql = r#"CREATE TABLE "AudioCreation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
    "account_id" BIGINT,
    CONSTRAINT "fk_AudioCreation_account_id" FOREIGN KEY ("account_id") REFERENCES "Account" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);"#;
        let legacy_variation_sql = r#"CREATE TABLE "AudioVariation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "creation_id" BIGINT
);"#;
        let legacy_sql = format!("{legacy_account_sql}\n{legacy_audio_sql}\n{legacy_variation_sql}");
        fs::write(project.join("dinoco/migrations/20240101000000_legacy/migration.sql"), legacy_sql)?;

        let db = connect(ServerDatabase::Postgres, &database_url).await?;
        db.execute(legacy_account_sql).await?;
        db.execute(legacy_audio_sql).await?;
        db.execute(legacy_variation_sql).await?;
        db.execute("INSERT INTO \"Account\" (name) VALUES ('preserved')").await?;
        db.execute("INSERT INTO \"AudioCreation\" (account_id) VALUES (1)").await?;
        db.execute("INSERT INTO \"AudioVariation\" (creation_id) VALUES (999)").await?;
        db.execute(
            "CREATE TABLE _dinoco_migrations (name TEXT PRIMARY KEY, applied_at TIMESTAMP, rollback_at TIMESTAMP)",
        )
        .await?;
        db.execute(
            "INSERT INTO _dinoco_migrations (name, applied_at, rollback_at) VALUES ('20240101000000_legacy', CURRENT_TIMESTAMP, NULL)",
        )
        .await?;
        drop(db);

        let generated = run_cli(&project, &database_url, &["migrate", "generate"], &[]);
        assert_success(&generated);
        let output = combined_output(&generated);
        assert!(output.contains("Upgraded 1 legacy migration"), "{output}");
        assert!(output.contains("Legacy migration history will be normalized"), "{output}");
        assert!(output.contains("NOT VALID constraints"), "{output}");
        assert_eq!(migration_dirs(&project).len(), 2);

        let generated_migration = migration_dirs(&project)
            .into_iter()
            .find(|path| path.file_name().and_then(|name| name.to_str()) != Some("20240101000000_legacy"))
            .expect("generated migration");
        let up_sql = fs::read_to_string(generated_migration.join("up.sql"))?;
        let down_sql = fs::read_to_string(generated_migration.join("down.sql"))?;
        assert!(up_sql.contains("ALTER TABLE \"Account\" RENAME TO \"account\";"), "{up_sql}");
        assert!(
            up_sql.contains("ALTER TABLE \"AudioCreation\" RENAME TO \"audio_creation\";"),
            "{up_sql}"
        );
        assert!(
            up_sql.contains("ALTER TABLE \"AudioVariation\" RENAME TO \"audio_variation\";"),
            "{up_sql}"
        );
        assert!(
            up_sql.contains("CONSTRAINT \"fk_audio_variation_creation_id\"") && up_sql.contains("NOT VALID;"),
            "{up_sql}"
        );
        assert!(!up_sql.contains("DROP TABLE \"Account\""), "{up_sql}");
        assert!(down_sql.contains("ALTER TABLE \"account\" RENAME TO \"Account\";"), "{down_sql}");

        let db = connect(ServerDatabase::Postgres, &database_url).await?;
        assert_eq!(db.count("SELECT COUNT(*) FROM account WHERE name = 'preserved'").await?, 1);
        assert_eq!(
            db.count(
                "SELECT COUNT(*) FROM audio_creation JOIN account ON account.id = audio_creation.account_id",
            )
            .await?,
            1
        );
        assert_eq!(db.count("SELECT COUNT(*) FROM audio_variation WHERE creation_id = 999").await?, 1);
        assert_eq!(
            db.count(
                "SELECT COUNT(*) FROM pg_constraint WHERE conname = 'fk_audio_variation_creation_id' AND NOT convalidated",
            )
            .await?,
            1
        );
        assert!(
            db.execute("INSERT INTO audio_variation (creation_id) VALUES (1000)").await.is_err(),
            "NOT VALID constraints must still protect new writes"
        );
        let schema = db.inspect_schema().await?;
        assert!(schema.tables.iter().any(|table| table.name == "account"));
        assert!(!schema.tables.iter().any(|table| table.name == "Account"));
        let audio_creation = schema
            .tables
            .iter()
            .find(|table| table.name == "audio_creation")
            .expect("renamed audio creation table");
        assert!(audio_creation.columns.iter().any(|column| column.name == "createdAt"));
        if let CliDatabase::Postgres(adapter) = &db {
            let (sql, _) = adapter.compile_find_query(FindQuery::new(
                &["id", "createdAt"],
                "audio_creation",
                -1,
                -1,
            ));
            assert!(sql.contains("\"createdAt\""), "{sql}");
        }
        Ok::<_, anyhow::Error>(())
    }
    .await;

    let _ = fs::remove_dir_all(&project);
    let cleanup = drop_database(ServerDatabase::Postgres, &database_name).await;
    outcome.and(cleanup)
}

#[tokio::test]
async fn postgres_run_recovers_a_failed_legacy_normalization_with_orphan_rows() -> anyhow::Result<()> {
    let suffix = format!("{}_{}_{}", std::process::id(), monotonic(), NEXT_TEST_ID.fetch_add(1, Ordering::Relaxed));
    let database_name = format!("dinoco_pg_legacy_recovery_{suffix}");
    create_database(ServerDatabase::Postgres, &database_name).await?;
    let database_url = format!("postgres://postgres:postgres@localhost:5432/{database_name}");
    let project = temporary_project("pg-legacy-recovery", &suffix);

    let outcome = async {
        let legacy_name = "20240101000000_legacy";
        let generated_name = "99999999999999_generated";
        fs::create_dir_all(project.join(format!("dinoco/migrations/{legacy_name}")))?;
        fs::create_dir_all(project.join(format!("dinoco/migrations/{generated_name}")))?;
        fs::write(
            project.join("dinoco/schema.dinoco"),
            r#"
config {
    database = "postgresql"
    database_url = env("DATABASE_URL")
}

model AudioCreation {
    id         Integer          @id @default(autoincrement())
    variations AudioVariation[]
}

model AudioVariation {
    id          Integer        @id @default(autoincrement())
    creation_id Integer?
    creation    AudioCreation? @relation(fields: [creation_id], references: [id], onUpdate: Cascade, onDelete: Cascade)
}
"#,
        )?;
        let legacy_sql = r#"CREATE TABLE "AudioCreation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
CREATE TABLE "AudioVariation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "creation_id" BIGINT
);"#;
        fs::write(project.join(format!("dinoco/migrations/{legacy_name}/migration.sql")), legacy_sql)?;

        let generated_sql = format!(
            "CREATE TABLE IF NOT EXISTS dinoco_migrations (name VARCHAR(255) PRIMARY KEY, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);\n\n\
             ALTER TABLE \"AudioCreation\" RENAME TO \"audio_creation\";\n\n\
             ALTER TABLE \"AudioVariation\" RENAME TO \"audio_variation\";\n\n\
             ALTER TABLE audio_variation ADD CONSTRAINT \"fk_audio_variation_creation_id\" FOREIGN KEY (creation_id) REFERENCES audio_creation (id) ON UPDATE CASCADE ON DELETE CASCADE;\n\n\
             INSERT INTO dinoco_migrations (name) VALUES ('{generated_name}') ON CONFLICT (name) DO NOTHING;"
        );
        fs::write(project.join(format!("dinoco/migrations/{generated_name}/up.sql")), generated_sql)?;
        fs::write(project.join(format!("dinoco/migrations/{generated_name}/down.sql")), "-- recovery fixture")?;

        let db = connect(ServerDatabase::Postgres, &database_url).await?;
        db.execute(
            "CREATE TABLE \"AudioCreation\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
        )
        .await?;
        db.execute(
            "CREATE TABLE \"AudioVariation\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"creation_id\" BIGINT)",
        )
        .await?;
        db.execute("INSERT INTO \"AudioVariation\" (creation_id) VALUES (999)").await?;
        db.execute(
            "CREATE TABLE _dinoco_migrations (name TEXT PRIMARY KEY, applied_at TIMESTAMP, rollback_at TIMESTAMP)",
        )
        .await?;
        db.execute(&format!(
            "INSERT INTO _dinoco_migrations (name, applied_at, rollback_at) VALUES ('{legacy_name}', CURRENT_TIMESTAMP, NULL)"
        ))
        .await?;
        drop(db);

        let run = run_cli(&project, &database_url, &["migrate", "run"], &[]);
        assert_success(&run);
        let output = combined_output(&run);
        assert!(output.contains("Recovering a pending generated legacy normalization"), "{output}");

        let db = connect(ServerDatabase::Postgres, &database_url).await?;
        assert_eq!(db.count("SELECT COUNT(*) FROM audio_variation WHERE creation_id = 999").await?, 1);
        assert_eq!(
            db.count(
                "SELECT COUNT(*) FROM pg_constraint WHERE conname = 'fk_audio_variation_creation_id' AND NOT convalidated",
            )
            .await?,
            1
        );
        assert_eq!(db.count(&format!("SELECT COUNT(*) FROM dinoco_migrations WHERE name = '{generated_name}'")).await?, 1);
        Ok::<_, anyhow::Error>(())
    }
    .await;

    let _ = fs::remove_dir_all(&project);
    let cleanup = drop_database(ServerDatabase::Postgres, &database_name).await;
    outcome.and(cleanup)
}

async fn exercise_server_migrations(database: ServerDatabase) -> anyhow::Result<()> {
    let adapter = match database {
        ServerDatabase::Postgres => "pg",
        ServerDatabase::Mysql => "mysql",
    };
    let suffix = format!("{}_{}_{}", std::process::id(), monotonic(), NEXT_TEST_ID.fetch_add(1, Ordering::Relaxed));
    let database_name = format!("dinoco_{adapter}_{suffix}");
    create_database(database, &database_name).await?;
    let database_url = match database {
        ServerDatabase::Postgres => format!("postgres://postgres:postgres@localhost:5432/{database_name}"),
        ServerDatabase::Mysql => format!("mysql://root:root@localhost:3306/{database_name}"),
    };
    let project = temporary_project(adapter, &suffix);
    write_schema(&project, database);

    let outcome = async {
        let initial = run_cli(&project, &database_url, &["migrate", "generate"], &[]);
        assert_success(&initial);
        assert_eq!(migration_dirs(&project).len(), 1);

        let db = connect(database, &database_url).await?;
        db.execute("INSERT INTO account (name) VALUES ('preserved')").await?;
        db.execute("DROP TABLE business").await?;
        db.execute("DROP TABLE address").await?;
        drop(db);

        let repair =
            run_cli(&project, &database_url, &["migrate", "generate"], &[("DINOCO_CLI_CONFIRM_DRIFT", "true")]);
        assert_success(&repair);
        let repair_output = combined_output(&repair);
        assert!(repair_output.contains("Database schema drift detected"), "{repair_output}");
        assert!(repair_output.contains("Missing table `business`"), "{repair_output}");
        assert!(repair_output.contains("Missing table `address`"), "{repair_output}");
        assert_eq!(migration_dirs(&project).len(), 1, "drift repair must not invent schema history");

        let db = connect(database, &database_url).await?;
        assert_eq!(db.count("SELECT COUNT(*) FROM account WHERE name = 'preserved'").await?, 1);
        let schema = db.inspect_schema().await?;
        assert!(schema.tables.iter().any(|table| table.name == "account"));
        assert!(schema.tables.iter().any(|table| table.name == "business"));
        assert!(schema.tables.iter().any(|table| table.name == "address"));
        let metadata = db.migration_metadata().await?;
        assert!(metadata.checksums_required);
        assert!(metadata.schema_snapshots_required);
        assert_eq!(metadata.checksums.as_ref().map(|items| items.len()), Some(1));
        assert_eq!(metadata.schema_snapshots.as_ref().map(|items| items.len()), Some(1));
        drop(db);

        let stable = run_cli(&project, &database_url, &["migrate", "generate"], &[]);
        assert_success(&stable);
        assert!(combined_output(&stable).contains("No schema changes were found"));

        let migration = migration_dirs(&project).into_iter().next().expect("initial migration");
        let up_path = migration.join("up.sql");
        let mut up_sql = fs::read_to_string(&up_path)?;
        up_sql.push_str("\n-- tampered after application\n");
        fs::write(&up_path, up_sql)?;
        let tampered = run_cli(&project, &database_url, &["migrate", "run"], &[]);
        assert!(!tampered.status.success(), "{}", combined_output(&tampered));
        assert!(combined_output(&tampered).to_ascii_lowercase().contains("checksum"));

        Ok::<_, anyhow::Error>(())
    }
    .await;

    let _ = fs::remove_dir_all(&project);
    let cleanup = drop_database(database, &database_name).await;
    outcome.and(cleanup)
}

async fn connect(database: ServerDatabase, url: &str) -> anyhow::Result<CliDatabase> {
    match database {
        ServerDatabase::Postgres => Ok(CliDatabase::Postgres(PostgresAdapter::direct(url).await?)),
        ServerDatabase::Mysql => Ok(CliDatabase::Mysql(MySqlAdapter::new(url))),
    }
}

async fn create_database(database: ServerDatabase, name: &str) -> anyhow::Result<()> {
    match database {
        ServerDatabase::Postgres => {
            let admin = PostgresAdapter::direct(POSTGRES_ADMIN_URL).await?;
            admin.execute(&format!("DROP DATABASE IF EXISTS {name} WITH (FORCE)"), &[]).await?;
            admin.execute(&format!("CREATE DATABASE {name}"), &[]).await?;
        }
        ServerDatabase::Mysql => {
            let admin = MySqlAdapter::new(MYSQL_ADMIN_URL);
            admin.execute(&format!("DROP DATABASE IF EXISTS {name}"), &[]).await?;
            admin.execute(&format!("CREATE DATABASE {name}"), &[]).await?;
        }
    }
    Ok(())
}

async fn drop_database(database: ServerDatabase, name: &str) -> anyhow::Result<()> {
    match database {
        ServerDatabase::Postgres => {
            let admin = PostgresAdapter::direct(POSTGRES_ADMIN_URL).await?;
            admin.execute(&format!("DROP DATABASE IF EXISTS {name} WITH (FORCE)"), &[]).await?;
        }
        ServerDatabase::Mysql => {
            let admin = MySqlAdapter::new(MYSQL_ADMIN_URL);
            admin.execute(&format!("DROP DATABASE IF EXISTS {name}"), &[]).await?;
        }
    }
    Ok(())
}

fn write_schema(project: &Path, database: ServerDatabase) {
    fs::create_dir_all(project.join("dinoco")).expect("dinoco directory");
    let provider = match database {
        ServerDatabase::Postgres => "postgresql",
        ServerDatabase::Mysql => "mysql",
    };
    fs::write(
        project.join("dinoco/schema.dinoco"),
        format!(
            r#"
config {{
    database = "{provider}"
    database_url = env("DATABASE_URL")
}}

model Account {{
    id         Integer    @id @default(autoincrement())
    name       String
    businesses Business[]
    profile    Profile?
}}

model Business {{
    id         Integer @id @default(autoincrement())
    account_id Integer
    account    Account? @relation(fields: [account_id], references: [id], onDelete: Cascade)
}}

model Profile {{
    id         Integer @id @default(autoincrement())
    account_id Integer @unique
    account    Account? @relation(fields: [account_id], references: [id], onDelete: Cascade)
}}

model Address {{
    id Integer @id @default(autoincrement())
}}
"#
        ),
    )
    .expect("schema");
}

fn temporary_project(adapter: &str, suffix: &str) -> PathBuf {
    let path = std::env::temp_dir().join(format!("dinoco-server-migration-{adapter}-{suffix}"));
    fs::create_dir(&path).expect("unique temporary project");
    path
}

fn run_cli(project: &Path, database_url: &str, args: &[&str], envs: &[(&str, &str)]) -> Output {
    let mut command = Command::new(env!("CARGO_BIN_EXE_dinoco_cli"));
    command
        .args(args)
        .env("DATABASE_URL", database_url)
        .env("DINOCO_CLI_CONFIRM_MIGRATION", "true")
        .current_dir(project);
    for (key, value) in envs {
        command.env(key, value);
    }
    command.output().expect("dinoco cli")
}

fn assert_success(output: &Output) {
    assert!(output.status.success(), "{}", combined_output(output));
}

fn combined_output(output: &Output) -> String {
    format!("{}\n{}", String::from_utf8_lossy(&output.stdout), String::from_utf8_lossy(&output.stderr))
}

fn migration_dirs(project: &Path) -> Vec<PathBuf> {
    let mut migrations = fs::read_dir(project.join("dinoco/migrations"))
        .expect("migrations")
        .map(|entry| entry.expect("migration entry").path())
        .filter(|path| path.is_dir())
        .collect::<Vec<_>>();
    migrations.sort();
    migrations
}

fn monotonic() -> u128 {
    SystemTime::now().duration_since(UNIX_EPOCH).expect("time").as_nanos()
}
