// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './../src/routes/__layout'

const IndexImport = __tuono__internal__lazyLoadRoute(
  () => import('./../src/routes/index'),
)
const versionIndexImport = __tuono__internal__lazyLoadRoute(
  () => import('./../src/routes/[version]/index'),
)
const versiongroupitemImport = __tuono__internal__lazyLoadRoute(
  () => import('./../src/routes/[version]/[group]/[item]'),
)
const versiongroupIndexImport = __tuono__internal__lazyLoadRoute(
  () => import('./../src/routes/[version]/[group]/index'),
)
const versiongroupitemsubitemImport = __tuono__internal__lazyLoadRoute(
  () => import('./../src/routes/[version]/[group]/[item]/[subitem]'),
)

const rootRoute = createRoute({ isRoot: true, component: RootLayoutImport })

const Index = createRoute({ component: IndexImport })
const versionIndex = createRoute({ component: versionIndexImport })
const versiongroupitem = createRoute({ component: versiongroupitemImport })
const versiongroupIndex = createRoute({ component: versiongroupIndexImport })
const versiongroupitemsubitem = createRoute({
  component: versiongroupitemsubitemImport,
})

// Create/Update Routes

const IndexRoute = Index.update({
  path: '/',
  getParentRoute: () => rootRoute,
  hasHandler: true,
  filePath: '/',
})

const versionIndexRoute = versionIndex.update({
  path: '/[version]',
  getParentRoute: () => rootRoute,
  filePath: '/[version]/',
})

const versiongroupitemRoute = versiongroupitem.update({
  path: '/[version]/[group]/[item]',
  getParentRoute: () => rootRoute,
  filePath: '/[version]/[group]/[item]',
})

const versiongroupIndexRoute = versiongroupIndex.update({
  path: '/[version]/[group]',
  getParentRoute: () => rootRoute,
  filePath: '/[version]/[group]/',
})

const versiongroupitemsubitemRoute = versiongroupitemsubitem.update({
  path: '/[version]/[group]/[item]/[subitem]',
  getParentRoute: () => rootRoute,
  filePath: '/[version]/[group]/[item]/[subitem]',
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  versionIndexRoute,
  versiongroupIndexRoute,
  versiongroupitemRoute,
  versiongroupitemsubitemRoute,
])
