// ==============================================================
// =================== DINOCO MANAGED FILE =======================
// ==============================================================
// This file is generated and managed by Dinoco.
// Do not edit this file manually.
// Any manual changes will be overwritten the next time Dinoco runs.
// ==============================================================

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
#![allow(unused_variables)]

use dinoco::{DinocoClient, DinocoClientConfig, DinocoResult, QueueWorkers, SqliteAdapter};

pub mod models;
pub use models::*;

fn __dinoco_sqlite_base_url(url: String) -> String {
    fn is_windows_absolute(path: &str) -> bool {
        let bytes = path.as_bytes();

        bytes.len() > 2
            && bytes[1] == b':'
            && (bytes[2] == b'/' || bytes[2] == b'\\')
            && bytes[0].is_ascii_alphabetic()
    }

    if !url.starts_with("file:") {
        return url;
    }

    let raw = &url["file:".len()..];

    if raw.is_empty()
        || raw == ":memory:"
        || raw.starts_with('/')
        || raw.starts_with("//")
        || is_windows_absolute(raw)
    {
        return url;
    }

    let (path_part, suffix) = match raw.split_once('?') {
        Some((path, query)) => (path, format!("?{}", query)),
        None => (raw, String::new()),
    };

    if path_part == ":memory:"
        || path_part.starts_with("dinoco/")
        || path_part.starts_with("./dinoco/")
    {
        return url;
    }

    let normalized_relative = path_part.strip_prefix("./").unwrap_or(path_part);
    let normalized_path = std::path::Path::new("dinoco").join(normalized_relative);
    let normalized_path = normalized_path.to_string_lossy().replace('\\', "/");

    format!("file:{}{}", normalized_path, suffix)
}

pub async fn create_connection(config: DinocoClientConfig) -> DinocoResult<DinocoClient<SqliteAdapter>> {
    let database_url = __dinoco_sqlite_base_url(std::env::var("DATABASE_URL").expect("missing environment variable for Dinoco client generation"));
    DinocoClient::<SqliteAdapter>::new(database_url, vec![], config).await
}
