import type { DocsLocale } from '../jsons/versions';

const messages = {
	'en-us': {
		description: 'Official documentation',
		donate: 'Support',
		github: 'GitHub',
		inPageLabel: 'On this page',
		localeLabel: 'Language',
		menuLabel: 'Open documentation menu',
		closeMenuLabel: 'Close documentation menu',
		themeDark: 'Use dark theme',
		themeLight: 'Use light theme',
		locales: {
			'en-us': 'English',
			'pt-br': 'Portuguese',
		},
		navigation: {
			closeSubItems: 'Collapse subitems',
			openSubItems: 'Expand subitems',
			previous: 'Previous',
			next: 'Next',
			title: 'Documentation navigation',
		},
		code: {
			copy: 'Copy',
			copied: 'Copied',
			copyLabel: 'Copy code',
			copiedLabel: 'Code copied',
		},
		home: {
			tagline: 'Open-source tools for building fast, reliable software.',
			heroTitle: 'Dinoco',
			heroSubtitle: 'An open-source ecosystem of Rust tools for modeling data, running migrations, and querying databases with confidence.',
			getStarted: 'Get Started',
			viewDocs: 'Documentation',
			viewGithub: 'GitHub',
			projectsTitle: 'Projects',
			projectsSubtitle: 'One ecosystem, built one focused tool at a time.',
			ormName: 'Dinoco ORM',
			ormDescription: 'A schema-driven ORM for Rust: one schema for PostgreSQL, MySQL, and SQLite, with generated typed entities, migrations, and a query API checked at compile time.',
			ormStatus: 'Available now',
			ormCta: 'Read the docs',
			comingSoonBadge: 'Coming soon',
			supersonicName: 'Supersonic',
			supersonicDescription: "A future Dinoco project. There's nothing to show yet — follow the GitHub organization for updates.",
			dinocoDbName: 'DinocoDB',
			dinocoDbDescription: "A future Dinoco project. There's nothing to show yet — follow the GitHub organization for updates.",
			openSourceTitle: 'Open source, by design',
			openSourceBody: 'Every Dinoco project is developed in the open on GitHub, under the Apache 2.0 license. Issues, discussions, and pull requests are how the roadmap gets decided.',
			openSourceCta: 'Contribute on GitHub',
		},
		footer: {
			tagline: 'Open-source tools for building fast, reliable software.',
			product: 'Product',
			resources: 'Resources',
			docs: 'Documentation',
			vscode: 'VS Code extension',
			cli: 'CLI reference',
			community: 'Community',
			github: 'GitHub',
			issues: 'Report an issue',
			support: 'Support the project',
			license: 'Apache 2.0 License',
		},
	},
	'pt-br': {
		description: 'Documentação oficial',
		donate: 'Apoiar',
		github: 'GitHub',
		inPageLabel: 'Nesta página',
		localeLabel: 'Idioma',
		menuLabel: 'Abrir menu da documentação',
		closeMenuLabel: 'Fechar menu da documentação',
		themeDark: 'Usar tema escuro',
		themeLight: 'Usar tema claro',
		locales: {
			'en-us': 'Inglês',
			'pt-br': 'Português',
		},
		navigation: {
			closeSubItems: 'Fechar subitens',
			openSubItems: 'Abrir subitens',
			previous: 'Anterior',
			next: 'Próximo',
			title: 'Navegação da documentação',
		},
		code: {
			copy: 'Copiar',
			copied: 'Copiado',
			copyLabel: 'Copiar código',
			copiedLabel: 'Código copiado',
		},
		home: {
			tagline: 'Ferramentas open-source para construir software rápido e confiável.',
			heroTitle: 'Dinoco',
			heroSubtitle: 'Um ecossistema open-source de ferramentas em Rust para modelar dados, rodar migrations e consultar bancos de dados com confiança.',
			getStarted: 'Começar',
			viewDocs: 'Documentação',
			viewGithub: 'GitHub',
			projectsTitle: 'Projetos',
			projectsSubtitle: 'Um ecossistema, construído uma ferramenta focada de cada vez.',
			ormName: 'Dinoco ORM',
			ormDescription: 'Um ORM orientado a schema para Rust: um schema para PostgreSQL, MySQL e SQLite, com entidades tipadas geradas, migrations e uma API de consultas verificada em tempo de compilação.',
			ormStatus: 'Disponível agora',
			ormCta: 'Ler a documentação',
			comingSoonBadge: 'Em breve',
			supersonicName: 'Supersonic',
			supersonicDescription: 'Um futuro projeto Dinoco. Ainda não há nada para mostrar — acompanhe a organização no GitHub para novidades.',
			dinocoDbName: 'DinocoDB',
			dinocoDbDescription: 'Um futuro projeto Dinoco. Ainda não há nada para mostrar — acompanhe a organização no GitHub para novidades.',
			openSourceTitle: 'Open source por natureza',
			openSourceBody: 'Todo projeto Dinoco é desenvolvido abertamente no GitHub, sob a licença Apache 2.0. Issues, discussões e pull requests são como o roadmap é decidido.',
			openSourceCta: 'Contribua no GitHub',
		},
		footer: {
			tagline: 'Ferramentas open-source para construir software rápido e confiável.',
			product: 'Produto',
			resources: 'Recursos',
			docs: 'Documentação',
			vscode: 'Extensão do VS Code',
			cli: 'Referência da CLI',
			community: 'Comunidade',
			github: 'GitHub',
			issues: 'Reportar um problema',
			support: 'Apoiar o projeto',
			license: 'Licença Apache 2.0',
		},
	},
} as const;

export function getIntlMessages(locale: DocsLocale) {
	return messages[locale] ?? messages['en-us'];
}
