[package]
name = "dinoco"
version = "1.2.7"
edition = "2024"
license = "Apache-2.0"
description = "A modern Rust ORM for schema-driven queries, migrations, and database operations."
homepage = "https://docs.dinoco.io"
repository = "https://github.com/dinoco-rs/dinoco"
readme = "../../crates.md"
keywords = ["orm", "database", "sql", "migrations", "rust"]

[dependencies]
dinoco_engine = { path = "../dinoco_engine", version = "1.2.7" }
dinoco_derives = { path = "../dinoco_derives", version = "1.2.7" }
dinoco_cli = { path = "../dinoco_cli", version = "1.2.7" }

uuid = { version = "1.18.1", features = ["v7"] }

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread", "sync"] }
async-trait = "0.1.89"
anyhow = "1.0.103"
futures = "0.3.31"
thiserror = "2"
