// ==============================================================
// =================== DINOCO MANAGED FILE =======================
// ==============================================================
// This file is generated and managed by Dinoco.
// Do not edit this file manually.
// Any manual changes will be overwritten the next time Dinoco runs.
// ==============================================================

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
#![allow(unused_variables)]

#[derive(Debug, Clone, PartialEq, Eq, Default, dinoco::serde::Serialize, dinoco::serde::Deserialize)]
#[serde(crate = "dinoco::serde")]
pub enum PlayerGender {
    #[default]
    #[serde(rename = "male")]
    male,
    #[serde(rename = "female")]
    female,
}

impl TryFrom<dinoco::DinocoValue> for PlayerGender {
    type Error = dinoco::DinocoError;

    fn try_from(value: dinoco::DinocoValue) -> Result<Self, Self::Error> {
        let value = match value {
            dinoco::DinocoValue::String(value) => value,
            dinoco::DinocoValue::Enum(_, value) => value,
            dinoco::DinocoValue::Bytes(value) => String::from_utf8(value)
                .map_err(|_| dinoco::DinocoError::ParseError("Invalid UTF-8 enum value".into()))?,
            _ => return Err(dinoco::DinocoError::ParseError("Expected enum string value".into())),
        };

        match value.as_str() {
            "male" => Ok(Self::male),
            "female" => Ok(Self::female),
            _ => Err(dinoco::DinocoError::ParseError(format!("Invalid value '{}' for enum PlayerGender", value))),
        }
    }
}

impl dinoco::IntoDinocoValue for PlayerGender {
    fn into_dinoco_value(self) -> dinoco::DinocoValue {
        dinoco::DinocoValue::Enum("PlayerGender".to_string(), match self {
            Self::male => "male".to_string(),
            Self::female => "female".to_string(),
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default, dinoco::serde::Serialize, dinoco::serde::Deserialize)]
#[serde(crate = "dinoco::serde")]
pub enum PlayerOffice {
    #[default]
    #[serde(rename = "developer")]
    developer,
    #[serde(rename = "director")]
    director,
    #[serde(rename = "administrator")]
    administrator,
    #[serde(rename = "moderator")]
    moderator,
    #[serde(rename = "helper")]
    helper,
    #[serde(rename = "youtuber")]
    youtuber,
    #[serde(rename = "member")]
    member,
}

impl TryFrom<dinoco::DinocoValue> for PlayerOffice {
    type Error = dinoco::DinocoError;

    fn try_from(value: dinoco::DinocoValue) -> Result<Self, Self::Error> {
        let value = match value {
            dinoco::DinocoValue::String(value) => value,
            dinoco::DinocoValue::Enum(_, value) => value,
            dinoco::DinocoValue::Bytes(value) => String::from_utf8(value)
                .map_err(|_| dinoco::DinocoError::ParseError("Invalid UTF-8 enum value".into()))?,
            _ => return Err(dinoco::DinocoError::ParseError("Expected enum string value".into())),
        };

        match value.as_str() {
            "developer" => Ok(Self::developer),
            "director" => Ok(Self::director),
            "administrator" => Ok(Self::administrator),
            "moderator" => Ok(Self::moderator),
            "helper" => Ok(Self::helper),
            "youtuber" => Ok(Self::youtuber),
            "member" => Ok(Self::member),
            _ => Err(dinoco::DinocoError::ParseError(format!("Invalid value '{}' for enum PlayerOffice", value))),
        }
    }
}

impl dinoco::IntoDinocoValue for PlayerOffice {
    fn into_dinoco_value(self) -> dinoco::DinocoValue {
        dinoco::DinocoValue::Enum("PlayerOffice".to_string(), match self {
            Self::developer => "developer".to_string(),
            Self::director => "director".to_string(),
            Self::administrator => "administrator".to_string(),
            Self::moderator => "moderator".to_string(),
            Self::helper => "helper".to_string(),
            Self::youtuber => "youtuber".to_string(),
            Self::member => "member".to_string(),
        })
    }
}

