// ==============================================================
// =================== DINOCO MANAGED FILE =======================
// ==============================================================
// This file is generated and managed by Dinoco.
// Do not edit this file manually.
// Any manual changes will be overwritten the next time Dinoco runs.
// ==============================================================

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
#![allow(unused_variables)]

use dinoco::{AdapterDialect, FindAndUpdateModel, InsertModel, IntoDinocoValue, Model, Projection, RelationField, RelationMutationModel, RelationMutationWhere, RelationScalarField, RelationWritePlan, Rowable, ScalarField, UpdateField, UpdateModel};
use super::{character::Character, character_outfit::CharacterOutfit, player_reset_password::PlayerResetPassword, player_token::PlayerToken, player_verify::PlayerVerify, subscription::Subscription};

#[derive(Debug, Clone, dinoco::serde::Serialize, dinoco::serde::Deserialize, Rowable)]
#[serde(crate = "dinoco::serde")]
pub struct Player {
    pub id: dinoco::Uuid,
    pub nicknameColor: String,
    pub nickname: String,
    pub password: String,
    pub levelStepRemaining: i64,
    pub levelStep: i64,
    pub level: i64,
    pub stars: i64,
    pub sleep: i64,
    pub sleepPercent: i64,
    pub health: i64,
    pub healthPercent: i64,
    pub thirst: i64,
    pub thirstPercent: i64,
    pub hunger: i64,
    pub hungerPercent: i64,
    pub email: String,
    pub emailVerified: bool,
    pub watchedTutorial: bool,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub heading: f64,
    pub office: super::enums::PlayerOffice,
    pub gender: super::enums::PlayerGender,
    pub createdAt: dinoco::DateTimeUtc<dinoco::Utc>,
}

impl Player {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Default for Player {
    fn default() -> Self {
        Self {
            id: dinoco::Uuid::new(),
            nicknameColor: "#ffffff".to_string(),
            nickname: String::new(),
            password: String::new(),
            levelStepRemaining: 600,
            levelStep: 0,
            level: 0,
            stars: 0,
            sleep: 7200,
            sleepPercent: 100,
            health: 360,
            healthPercent: 100,
            thirst: 900,
            thirstPercent: 100,
            hunger: 1500,
            hungerPercent: 100,
            email: String::new(),
            emailVerified: false,
            watchedTutorial: false,
            x: 0.0,
            y: 0.0,
            z: 0.0,
            heading: 0.0,
            office: <super::enums::PlayerOffice as Default>::default(),
            gender: <super::enums::PlayerGender as Default>::default(),
            createdAt: dinoco::Utc::now(),
        }
    }
}

pub struct PlayerWhere {
    pub id: ScalarField<String>,
    pub nicknameColor: ScalarField<String>,
    pub nickname: ScalarField<String>,
    pub password: ScalarField<String>,
    pub levelStepRemaining: ScalarField<i64>,
    pub levelStep: ScalarField<i64>,
    pub level: ScalarField<i64>,
    pub stars: ScalarField<i64>,
    pub sleep: ScalarField<i64>,
    pub sleepPercent: ScalarField<i64>,
    pub health: ScalarField<i64>,
    pub healthPercent: ScalarField<i64>,
    pub thirst: ScalarField<i64>,
    pub thirstPercent: ScalarField<i64>,
    pub hunger: ScalarField<i64>,
    pub hungerPercent: ScalarField<i64>,
    pub email: ScalarField<String>,
    pub emailVerified: ScalarField<bool>,
    pub watchedTutorial: ScalarField<bool>,
    pub x: ScalarField<f64>,
    pub y: ScalarField<f64>,
    pub z: ScalarField<f64>,
    pub heading: ScalarField<f64>,
    pub office: ScalarField<super::enums::PlayerOffice>,
    pub gender: ScalarField<super::enums::PlayerGender>,
    pub createdAt: ScalarField<dinoco::DateTimeUtc<dinoco::Utc>>,
}

pub struct PlayerUpdate {
    pub nicknameColor: UpdateField<String>,
    pub nickname: UpdateField<String>,
    pub password: UpdateField<String>,
    pub levelStepRemaining: UpdateField<i64>,
    pub levelStep: UpdateField<i64>,
    pub level: UpdateField<i64>,
    pub stars: UpdateField<i64>,
    pub sleep: UpdateField<i64>,
    pub sleepPercent: UpdateField<i64>,
    pub health: UpdateField<i64>,
    pub healthPercent: UpdateField<i64>,
    pub thirst: UpdateField<i64>,
    pub thirstPercent: UpdateField<i64>,
    pub hunger: UpdateField<i64>,
    pub hungerPercent: UpdateField<i64>,
    pub email: UpdateField<String>,
    pub emailVerified: UpdateField<bool>,
    pub watchedTutorial: UpdateField<bool>,
    pub x: UpdateField<f64>,
    pub y: UpdateField<f64>,
    pub z: UpdateField<f64>,
    pub heading: UpdateField<f64>,
    pub office: UpdateField<super::enums::PlayerOffice>,
    pub gender: UpdateField<super::enums::PlayerGender>,
    pub createdAt: UpdateField<dinoco::DateTimeUtc<dinoco::Utc>>,
}

pub struct PlayerRelationWhere {
    pub id: RelationScalarField<String>,
    pub nicknameColor: RelationScalarField<String>,
    pub nickname: RelationScalarField<String>,
    pub password: RelationScalarField<String>,
    pub levelStepRemaining: RelationScalarField<i64>,
    pub levelStep: RelationScalarField<i64>,
    pub level: RelationScalarField<i64>,
    pub stars: RelationScalarField<i64>,
    pub sleep: RelationScalarField<i64>,
    pub sleepPercent: RelationScalarField<i64>,
    pub health: RelationScalarField<i64>,
    pub healthPercent: RelationScalarField<i64>,
    pub thirst: RelationScalarField<i64>,
    pub thirstPercent: RelationScalarField<i64>,
    pub hunger: RelationScalarField<i64>,
    pub hungerPercent: RelationScalarField<i64>,
    pub email: RelationScalarField<String>,
    pub emailVerified: RelationScalarField<bool>,
    pub watchedTutorial: RelationScalarField<bool>,
    pub x: RelationScalarField<f64>,
    pub y: RelationScalarField<f64>,
    pub z: RelationScalarField<f64>,
    pub heading: RelationScalarField<f64>,
    pub office: RelationScalarField<super::enums::PlayerOffice>,
    pub gender: RelationScalarField<super::enums::PlayerGender>,
    pub createdAt: RelationScalarField<dinoco::DateTimeUtc<dinoco::Utc>>,
}

impl PlayerRelationWhere {
    pub fn new(relation_name: &'static str) -> RelationMutationWhere<Self> {
        RelationMutationWhere::new(Self {
            id: RelationScalarField::new(relation_name, "id"),
            nicknameColor: RelationScalarField::new(relation_name, "nicknameColor"),
            nickname: RelationScalarField::new(relation_name, "nickname"),
            password: RelationScalarField::new(relation_name, "password"),
            levelStepRemaining: RelationScalarField::new(relation_name, "levelStepRemaining"),
            levelStep: RelationScalarField::new(relation_name, "levelStep"),
            level: RelationScalarField::new(relation_name, "level"),
            stars: RelationScalarField::new(relation_name, "stars"),
            sleep: RelationScalarField::new(relation_name, "sleep"),
            sleepPercent: RelationScalarField::new(relation_name, "sleepPercent"),
            health: RelationScalarField::new(relation_name, "health"),
            healthPercent: RelationScalarField::new(relation_name, "healthPercent"),
            thirst: RelationScalarField::new(relation_name, "thirst"),
            thirstPercent: RelationScalarField::new(relation_name, "thirstPercent"),
            hunger: RelationScalarField::new(relation_name, "hunger"),
            hungerPercent: RelationScalarField::new(relation_name, "hungerPercent"),
            email: RelationScalarField::new(relation_name, "email"),
            emailVerified: RelationScalarField::new(relation_name, "emailVerified"),
            watchedTutorial: RelationScalarField::new(relation_name, "watchedTutorial"),
            x: RelationScalarField::new(relation_name, "x"),
            y: RelationScalarField::new(relation_name, "y"),
            z: RelationScalarField::new(relation_name, "z"),
            heading: RelationScalarField::new(relation_name, "heading"),
            office: RelationScalarField::new(relation_name, "office"),
            gender: RelationScalarField::new(relation_name, "gender"),
            createdAt: RelationScalarField::new(relation_name, "createdAt"),
        })
    }
}

#[derive(Default)]
pub struct PlayerInclude {}

#[derive(Default)]
pub struct PlayerRelations {}

impl Projection<Player> for Player {
    fn columns() -> &'static [&'static str] {
        &[
            "id",
            "nicknameColor",
            "nickname",
            "password",
            "levelStepRemaining",
            "levelStep",
            "level",
            "stars",
            "sleep",
            "sleepPercent",
            "health",
            "healthPercent",
            "thirst",
            "thirstPercent",
            "hunger",
            "hungerPercent",
            "email",
            "emailVerified",
            "watchedTutorial",
            "x",
            "y",
            "z",
            "heading",
            "office",
            "gender",
            "createdAt",
        ]
    }
}

impl InsertModel for Player {
    fn insert_columns() -> &'static [&'static str] {
        &[
            "id",
            "nicknameColor",
            "nickname",
            "password",
            "levelStepRemaining",
            "levelStep",
            "level",
            "stars",
            "sleep",
            "sleepPercent",
            "health",
            "healthPercent",
            "thirst",
            "thirstPercent",
            "hunger",
            "hungerPercent",
            "email",
            "emailVerified",
            "watchedTutorial",
            "x",
            "y",
            "z",
            "heading",
            "office",
            "gender",
            "createdAt",
        ]
    }

    fn into_insert_row(self) -> Vec<dinoco::DinocoValue> {
        vec![
            self.id.into_dinoco_value(),
            self.nicknameColor.into_dinoco_value(),
            self.nickname.into_dinoco_value(),
            self.password.into_dinoco_value(),
            self.levelStepRemaining.into_dinoco_value(),
            self.levelStep.into_dinoco_value(),
            self.level.into_dinoco_value(),
            self.stars.into_dinoco_value(),
            self.sleep.into_dinoco_value(),
            self.sleepPercent.into_dinoco_value(),
            self.health.into_dinoco_value(),
            self.healthPercent.into_dinoco_value(),
            self.thirst.into_dinoco_value(),
            self.thirstPercent.into_dinoco_value(),
            self.hunger.into_dinoco_value(),
            self.hungerPercent.into_dinoco_value(),
            self.email.into_dinoco_value(),
            self.emailVerified.into_dinoco_value(),
            self.watchedTutorial.into_dinoco_value(),
            self.x.into_dinoco_value(),
            self.y.into_dinoco_value(),
            self.z.into_dinoco_value(),
            self.heading.into_dinoco_value(),
            self.office.into_dinoco_value(),
            self.gender.into_dinoco_value(),
            self.createdAt.into_dinoco_value(),
        ]
    }

    fn insert_identity_conditions(&self) -> Vec<dinoco::Expression> {
        vec![
            dinoco::Expression::Column("id".to_string()).eq(self.id.clone().into_dinoco_value()),
        ]
    }

    fn validate_insert(&self) -> dinoco::DinocoResult<()> {
        if self.nickname.trim().is_empty() {
            return Err(dinoco::DinocoError::ParseError("Field 'Player.nickname' is required for insert and cannot be empty".to_string()));
        }
        if self.password.trim().is_empty() {
            return Err(dinoco::DinocoError::ParseError("Field 'Player.password' is required for insert and cannot be empty".to_string()));
        }
        if self.email.trim().is_empty() {
            return Err(dinoco::DinocoError::ParseError("Field 'Player.email' is required for insert and cannot be empty".to_string()));
        }
        Ok(())
    }
}

impl UpdateModel for Player {
    fn update_columns() -> &'static [&'static str] {
        &[
            "nicknameColor",
            "nickname",
            "password",
            "levelStepRemaining",
            "levelStep",
            "level",
            "stars",
            "sleep",
            "sleepPercent",
            "health",
            "healthPercent",
            "thirst",
            "thirstPercent",
            "hunger",
            "hungerPercent",
            "email",
            "emailVerified",
            "watchedTutorial",
            "x",
            "y",
            "z",
            "heading",
            "office",
            "gender",
            "createdAt",
        ]
    }

    fn into_update_row(self) -> Vec<dinoco::DinocoValue> {
        vec![
            self.nicknameColor.into_dinoco_value(),
            self.nickname.into_dinoco_value(),
            self.password.into_dinoco_value(),
            self.levelStepRemaining.into_dinoco_value(),
            self.levelStep.into_dinoco_value(),
            self.level.into_dinoco_value(),
            self.stars.into_dinoco_value(),
            self.sleep.into_dinoco_value(),
            self.sleepPercent.into_dinoco_value(),
            self.health.into_dinoco_value(),
            self.healthPercent.into_dinoco_value(),
            self.thirst.into_dinoco_value(),
            self.thirstPercent.into_dinoco_value(),
            self.hunger.into_dinoco_value(),
            self.hungerPercent.into_dinoco_value(),
            self.email.into_dinoco_value(),
            self.emailVerified.into_dinoco_value(),
            self.watchedTutorial.into_dinoco_value(),
            self.x.into_dinoco_value(),
            self.y.into_dinoco_value(),
            self.z.into_dinoco_value(),
            self.heading.into_dinoco_value(),
            self.office.into_dinoco_value(),
            self.gender.into_dinoco_value(),
            self.createdAt.into_dinoco_value(),
        ]
    }

    fn update_identity_conditions(&self) -> Vec<dinoco::Expression> {
        vec![
            dinoco::Expression::Column("id".to_string()).eq(self.id.clone().into_dinoco_value()),
        ]
    }

    fn validate_update(&self) -> dinoco::DinocoResult<()> {
        Ok(())
    }
}

impl Default for PlayerWhere {
    fn default() -> Self {
        Self {
            id: ScalarField::new("id"),
            nicknameColor: ScalarField::new("nicknameColor"),
            nickname: ScalarField::new("nickname"),
            password: ScalarField::new("password"),
            levelStepRemaining: ScalarField::new("levelStepRemaining"),
            levelStep: ScalarField::new("levelStep"),
            level: ScalarField::new("level"),
            stars: ScalarField::new("stars"),
            sleep: ScalarField::new("sleep"),
            sleepPercent: ScalarField::new("sleepPercent"),
            health: ScalarField::new("health"),
            healthPercent: ScalarField::new("healthPercent"),
            thirst: ScalarField::new("thirst"),
            thirstPercent: ScalarField::new("thirstPercent"),
            hunger: ScalarField::new("hunger"),
            hungerPercent: ScalarField::new("hungerPercent"),
            email: ScalarField::new("email"),
            emailVerified: ScalarField::new("emailVerified"),
            watchedTutorial: ScalarField::new("watchedTutorial"),
            x: ScalarField::new("x"),
            y: ScalarField::new("y"),
            z: ScalarField::new("z"),
            heading: ScalarField::new("heading"),
            office: ScalarField::new("office"),
            gender: ScalarField::new("gender"),
            createdAt: ScalarField::new("createdAt"),
        }
    }
}

impl Default for PlayerUpdate {
    fn default() -> Self {
        Self {
            nicknameColor: UpdateField::new("nicknameColor"),
            nickname: UpdateField::new("nickname"),
            password: UpdateField::new("password"),
            levelStepRemaining: UpdateField::new("levelStepRemaining"),
            levelStep: UpdateField::new("levelStep"),
            level: UpdateField::new("level"),
            stars: UpdateField::new("stars"),
            sleep: UpdateField::new("sleep"),
            sleepPercent: UpdateField::new("sleepPercent"),
            health: UpdateField::new("health"),
            healthPercent: UpdateField::new("healthPercent"),
            thirst: UpdateField::new("thirst"),
            thirstPercent: UpdateField::new("thirstPercent"),
            hunger: UpdateField::new("hunger"),
            hungerPercent: UpdateField::new("hungerPercent"),
            email: UpdateField::new("email"),
            emailVerified: UpdateField::new("emailVerified"),
            watchedTutorial: UpdateField::new("watchedTutorial"),
            x: UpdateField::new("x"),
            y: UpdateField::new("y"),
            z: UpdateField::new("z"),
            heading: UpdateField::new("heading"),
            office: UpdateField::new("office"),
            gender: UpdateField::new("gender"),
            createdAt: UpdateField::new("createdAt"),
        }
    }
}

impl PlayerInclude {
    pub fn tokens(&self) -> RelationField<super::player_token::PlayerToken> {
        RelationField::new("tokens")
    }
    pub fn resets(&self) -> RelationField<super::player_reset_password::PlayerResetPassword> {
        RelationField::new("resets")
    }
    pub fn verifies(&self) -> RelationField<super::player_verify::PlayerVerify> {
        RelationField::new("verifies")
    }
    pub fn character(&self) -> RelationField<super::character::Character> {
        RelationField::new("character")
    }
    pub fn outfits(&self) -> RelationField<super::character_outfit::CharacterOutfit> {
        RelationField::new("outfits")
    }
    pub fn subscriptions(&self) -> RelationField<super::subscription::Subscription> {
        RelationField::new("subscriptions")
    }
}

impl PlayerRelations {
    pub fn tokens(&self) -> RelationMutationWhere<super::player_token::PlayerTokenRelationWhere> {
        super::player_token::PlayerTokenRelationWhere::new("tokens")
    }
    pub fn resets(&self) -> RelationMutationWhere<super::player_reset_password::PlayerResetPasswordRelationWhere> {
        super::player_reset_password::PlayerResetPasswordRelationWhere::new("resets")
    }
    pub fn verifies(&self) -> RelationMutationWhere<super::player_verify::PlayerVerifyRelationWhere> {
        super::player_verify::PlayerVerifyRelationWhere::new("verifies")
    }
    pub fn character(&self) -> RelationMutationWhere<super::character::CharacterRelationWhere> {
        super::character::CharacterRelationWhere::new("character")
    }
    pub fn outfits(&self) -> RelationMutationWhere<super::character_outfit::CharacterOutfitRelationWhere> {
        super::character_outfit::CharacterOutfitRelationWhere::new("outfits")
    }
    pub fn subscriptions(&self) -> RelationMutationWhere<super::subscription::SubscriptionRelationWhere> {
        super::subscription::SubscriptionRelationWhere::new("subscriptions")
    }
}

impl Player {
    pub fn __dinoco_load_tokens<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Vec<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::player_token::PlayerToken>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: C,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::player_token::PlayerToken>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    Ok(Self {
                        item: C::from_row(row)?,
                        relation_key: row.get(C::columns().len())?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let base_statement = include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("PlayerToken").select(C::columns()));
            let adapter = client.read_adapter(false);
            let mut statement = base_statement;
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns().iter().map(|column| column.to_string()).collect::<Vec<_>>();
            }

            select_columns.push("playerId".to_string());
            statement.select = select_columns;
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, "playerId", "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let relation_keys = child_rows.iter().map(|row| row.relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_rows.into_iter().map(|row| row.item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, Vec<C>> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.entry(relation_key).or_default().push(child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or_default();
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_load_resets<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Vec<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::player_reset_password::PlayerResetPassword>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: C,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::player_reset_password::PlayerResetPassword>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    Ok(Self {
                        item: C::from_row(row)?,
                        relation_key: row.get(C::columns().len())?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let base_statement = include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("PlayerResetPassword").select(C::columns()));
            let adapter = client.read_adapter(false);
            let mut statement = base_statement;
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns().iter().map(|column| column.to_string()).collect::<Vec<_>>();
            }

            select_columns.push("playerId".to_string());
            statement.select = select_columns;
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, "playerId", "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let relation_keys = child_rows.iter().map(|row| row.relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_rows.into_iter().map(|row| row.item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, Vec<C>> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.entry(relation_key).or_default().push(child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or_default();
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_load_verifies<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Vec<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::player_verify::PlayerVerify>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: C,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::player_verify::PlayerVerify>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    Ok(Self {
                        item: C::from_row(row)?,
                        relation_key: row.get(C::columns().len())?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let base_statement = include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("PlayerVerify").select(C::columns()));
            let adapter = client.read_adapter(false);
            let mut statement = base_statement;
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns().iter().map(|column| column.to_string()).collect::<Vec<_>>();
            }

            select_columns.push("playerId".to_string());
            statement.select = select_columns;
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, "playerId", "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let relation_keys = child_rows.iter().map(|row| row.relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_rows.into_iter().map(|row| row.item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, Vec<C>> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.entry(relation_key).or_default().push(child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or_default();
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_load_character<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Vec<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::character::Character>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: C,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::character::Character>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    Ok(Self {
                        item: C::from_row(row)?,
                        relation_key: row.get(C::columns().len())?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let base_statement = include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("Character").select(C::columns()));
            let adapter = client.read_adapter(false);
            let mut statement = base_statement;
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns().iter().map(|column| column.to_string()).collect::<Vec<_>>();
            }

            select_columns.push("playerId".to_string());
            statement.select = select_columns;
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, "playerId", "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let relation_keys = child_rows.iter().map(|row| row.relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_rows.into_iter().map(|row| row.item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, Vec<C>> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.entry(relation_key).or_default().push(child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or_default();
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_load_outfits<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Vec<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::character_outfit::CharacterOutfit>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: C,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::character_outfit::CharacterOutfit>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    Ok(Self {
                        item: C::from_row(row)?,
                        relation_key: row.get(C::columns().len())?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let base_statement = include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("CharacterOutfit").select(C::columns()));
            let adapter = client.read_adapter(false);
            let mut statement = base_statement;
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns().iter().map(|column| column.to_string()).collect::<Vec<_>>();
            }

            select_columns.push("playerId".to_string());
            statement.select = select_columns;
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, "playerId", "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let relation_keys = child_rows.iter().map(|row| row.relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_rows.into_iter().map(|row| row.item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, Vec<C>> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.entry(relation_key).or_default().push(child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or_default();
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_load_subscriptions<'a, P, C, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        include: &'a dinoco::IncludeNode,
        client: &'a dinoco::DinocoClient<A>,
        read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut Vec<C> + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
        C: dinoco::Projection<super::subscription::Subscription>,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            struct DinocoChildRow<C> {
                item: C,
                relation_key: dinoco::Uuid,
            }

            impl<C> dinoco::DinocoRow for DinocoChildRow<C>
            where
                C: dinoco::Projection<super::subscription::Subscription>,
            {
                fn from_row<R: dinoco::DinocoGenericRow>(row: &R) -> dinoco::DinocoResult<Self> {
                    Ok(Self {
                        item: C::from_row(row)?,
                        relation_key: row.get(C::columns().len())?,
                    })
                }
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let base_statement = include.statement.clone().unwrap_or_else(|| dinoco::SelectStatement::new().from("Subscription").select(C::columns()));
            let adapter = client.read_adapter(false);
            let mut statement = base_statement;
            let mut select_columns = statement.select.clone();

            if select_columns.is_empty() {
                select_columns = C::columns().iter().map(|column| column.to_string()).collect::<Vec<_>>();
            }

            select_columns.push("playerId".to_string());
            statement.select = select_columns;
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let (sql, params) = if statement.limit.is_some() || statement.skip.is_some() {
                dinoco::QueryBuilder::build_partitioned_select(adapter.dialect(), &statement, "playerId", "__dinoco_row_num")
            } else {
                dinoco::QueryBuilder::build_select(adapter.dialect(), &statement)
            };
            let child_rows = adapter.query_as::<DinocoChildRow<C>>(&sql, &params).await?;
            let relation_keys = child_rows.iter().map(|row| row.relation_key.clone()).collect::<Vec<_>>();
            let mut children = child_rows.into_iter().map(|row| row.item).collect::<Vec<_>>();

            C::load_includes(&mut children, &include.includes, client, read_mode).await?;
            C::load_counts(&mut children, &include.counts, client, read_mode).await?;

            let mut grouped: HashMap<dinoco::Uuid, Vec<C>> = HashMap::new();

            for (relation_key, child) in relation_keys.into_iter().zip(children.into_iter()) {
                grouped.entry(relation_key).or_default().push(child);
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or_default();
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_count_tokens<'a, P, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        count: &'a dinoco::CountNode,
        client: &'a dinoco::DinocoClient<A>,
        _read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut usize + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            #[derive(Debug, Clone, dinoco::Rowable)]
            struct DinocoRelationCountRow {
                playerId: dinoco::Uuid,
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let adapter = client.read_adapter(false);
            let mut statement = count.statement.clone().unwrap_or_else(|| {
                dinoco::SelectStatement::new().from("PlayerToken").select(&["playerId"])
            });
            statement.select = vec!["playerId".to_string()];
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let rows = if statement.limit.is_some() || statement.skip.is_some() {
                let (sql, params) = dinoco::QueryBuilder::build_partitioned_select(
                    adapter.dialect(),
                    &statement,
                    "playerId",
                    "__dinoco_row_num",
                );
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            } else {
                let (sql, params) = dinoco::QueryBuilder::build_select(adapter.dialect(), &statement);
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            };

            let mut grouped: HashMap<dinoco::Uuid, usize> = HashMap::new();

            for row in rows {
                *grouped.entry(row.playerId).or_default() += 1;
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or(0);
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_count_resets<'a, P, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        count: &'a dinoco::CountNode,
        client: &'a dinoco::DinocoClient<A>,
        _read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut usize + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            #[derive(Debug, Clone, dinoco::Rowable)]
            struct DinocoRelationCountRow {
                playerId: dinoco::Uuid,
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let adapter = client.read_adapter(false);
            let mut statement = count.statement.clone().unwrap_or_else(|| {
                dinoco::SelectStatement::new().from("PlayerResetPassword").select(&["playerId"])
            });
            statement.select = vec!["playerId".to_string()];
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let rows = if statement.limit.is_some() || statement.skip.is_some() {
                let (sql, params) = dinoco::QueryBuilder::build_partitioned_select(
                    adapter.dialect(),
                    &statement,
                    "playerId",
                    "__dinoco_row_num",
                );
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            } else {
                let (sql, params) = dinoco::QueryBuilder::build_select(adapter.dialect(), &statement);
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            };

            let mut grouped: HashMap<dinoco::Uuid, usize> = HashMap::new();

            for row in rows {
                *grouped.entry(row.playerId).or_default() += 1;
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or(0);
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_count_verifies<'a, P, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        count: &'a dinoco::CountNode,
        client: &'a dinoco::DinocoClient<A>,
        _read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut usize + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            #[derive(Debug, Clone, dinoco::Rowable)]
            struct DinocoRelationCountRow {
                playerId: dinoco::Uuid,
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let adapter = client.read_adapter(false);
            let mut statement = count.statement.clone().unwrap_or_else(|| {
                dinoco::SelectStatement::new().from("PlayerVerify").select(&["playerId"])
            });
            statement.select = vec!["playerId".to_string()];
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let rows = if statement.limit.is_some() || statement.skip.is_some() {
                let (sql, params) = dinoco::QueryBuilder::build_partitioned_select(
                    adapter.dialect(),
                    &statement,
                    "playerId",
                    "__dinoco_row_num",
                );
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            } else {
                let (sql, params) = dinoco::QueryBuilder::build_select(adapter.dialect(), &statement);
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            };

            let mut grouped: HashMap<dinoco::Uuid, usize> = HashMap::new();

            for row in rows {
                *grouped.entry(row.playerId).or_default() += 1;
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or(0);
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_count_character<'a, P, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        count: &'a dinoco::CountNode,
        client: &'a dinoco::DinocoClient<A>,
        _read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut usize + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            #[derive(Debug, Clone, dinoco::Rowable)]
            struct DinocoRelationCountRow {
                playerId: dinoco::Uuid,
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let adapter = client.read_adapter(false);
            let mut statement = count.statement.clone().unwrap_or_else(|| {
                dinoco::SelectStatement::new().from("Character").select(&["playerId"])
            });
            statement.select = vec!["playerId".to_string()];
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let rows = if statement.limit.is_some() || statement.skip.is_some() {
                let (sql, params) = dinoco::QueryBuilder::build_partitioned_select(
                    adapter.dialect(),
                    &statement,
                    "playerId",
                    "__dinoco_row_num",
                );
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            } else {
                let (sql, params) = dinoco::QueryBuilder::build_select(adapter.dialect(), &statement);
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            };

            let mut grouped: HashMap<dinoco::Uuid, usize> = HashMap::new();

            for row in rows {
                *grouped.entry(row.playerId).or_default() += 1;
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or(0);
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_count_outfits<'a, P, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        count: &'a dinoco::CountNode,
        client: &'a dinoco::DinocoClient<A>,
        _read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut usize + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            #[derive(Debug, Clone, dinoco::Rowable)]
            struct DinocoRelationCountRow {
                playerId: dinoco::Uuid,
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let adapter = client.read_adapter(false);
            let mut statement = count.statement.clone().unwrap_or_else(|| {
                dinoco::SelectStatement::new().from("CharacterOutfit").select(&["playerId"])
            });
            statement.select = vec!["playerId".to_string()];
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let rows = if statement.limit.is_some() || statement.skip.is_some() {
                let (sql, params) = dinoco::QueryBuilder::build_partitioned_select(
                    adapter.dialect(),
                    &statement,
                    "playerId",
                    "__dinoco_row_num",
                );
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            } else {
                let (sql, params) = dinoco::QueryBuilder::build_select(adapter.dialect(), &statement);
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            };

            let mut grouped: HashMap<dinoco::Uuid, usize> = HashMap::new();

            for row in rows {
                *grouped.entry(row.playerId).or_default() += 1;
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or(0);
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

impl Player {
    pub fn __dinoco_count_subscriptions<'a, P, A>(
        item_keys: Vec<Option<dinoco::Uuid>>,
        count: &'a dinoco::CountNode,
        client: &'a dinoco::DinocoClient<A>,
        _read_mode: dinoco::ReadMode,
        relation_field: impl Fn(&mut P) -> &mut usize + Copy + Send + 'a,
    ) -> dinoco::IncludeLoaderFuture<'a, P>
    where
        A: dinoco::DinocoAdapter,
    {
        Box::pin(async move {
            use std::collections::HashMap;

            #[derive(Debug, Clone, dinoco::Rowable)]
            struct DinocoRelationCountRow {
                playerId: dinoco::Uuid,
            }

            let keys = item_keys.iter().flatten().cloned().collect::<Vec<_>>();

            if keys.is_empty() {
                return Ok(Box::new(|_: &mut [P]| {}) as dinoco::IncludeApplier<'a, P>);
            }

            let adapter = client.read_adapter(false);
            let mut statement = count.statement.clone().unwrap_or_else(|| {
                dinoco::SelectStatement::new().from("Subscription").select(&["playerId"])
            });
            statement.select = vec!["playerId".to_string()];
            statement.conditions.push(dinoco::Expression::Column("playerId".to_string()).in_values(keys.iter().cloned().map(dinoco::IntoDinocoValue::into_dinoco_value).collect()));

            let rows = if statement.limit.is_some() || statement.skip.is_some() {
                let (sql, params) = dinoco::QueryBuilder::build_partitioned_select(
                    adapter.dialect(),
                    &statement,
                    "playerId",
                    "__dinoco_row_num",
                );
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            } else {
                let (sql, params) = dinoco::QueryBuilder::build_select(adapter.dialect(), &statement);
                adapter.query_as::<DinocoRelationCountRow>(&sql, &params).await?
            };

            let mut grouped: HashMap<dinoco::Uuid, usize> = HashMap::new();

            for row in rows {
                *grouped.entry(row.playerId).or_default() += 1;
            }

            Ok(Box::new(move |items: &mut [P]| {
                for (item, key) in items.iter_mut().zip(item_keys.into_iter()) {
                    *relation_field(item) = key.and_then(|key| grouped.remove(&key)).unwrap_or(0);
                }
            }) as dinoco::IncludeApplier<'a, P>)
        })
    }
}

#[derive(Debug, Clone, dinoco::serde::Serialize, dinoco::serde::Deserialize)]
#[serde(crate = "dinoco::serde")]
pub enum PlayerConnection {
    Token(dinoco::Uuid),
    Reset(dinoco::Uuid),
    Verify(dinoco::Uuid),
    Character(dinoco::Uuid),
    Outfit(dinoco::Uuid),
    Subscription(dinoco::Uuid),
}

impl dinoco::InsertConnectionPayload<Player> for PlayerConnection {
    fn connection_updates(&self, parent: &Player) -> Vec<dinoco::ConnectionUpdatePlan> {
        match self {
            Self::Token(value) => vec![dinoco::ConnectionUpdatePlan {
                table_name: "PlayerToken",
                columns: &["playerId"],
                row: vec![parent.id.clone().into_dinoco_value()],
                conditions: vec![
                    dinoco::Expression::Column("id".to_string()).eq(value.clone().into_dinoco_value()),
                ],
            }],
            Self::Reset(value) => vec![dinoco::ConnectionUpdatePlan {
                table_name: "PlayerResetPassword",
                columns: &["playerId"],
                row: vec![parent.id.clone().into_dinoco_value()],
                conditions: vec![
                    dinoco::Expression::Column("id".to_string()).eq(value.clone().into_dinoco_value()),
                ],
            }],
            Self::Verify(value) => vec![dinoco::ConnectionUpdatePlan {
                table_name: "PlayerVerify",
                columns: &["playerId"],
                row: vec![parent.id.clone().into_dinoco_value()],
                conditions: vec![
                    dinoco::Expression::Column("id".to_string()).eq(value.clone().into_dinoco_value()),
                ],
            }],
            Self::Character(value) => vec![dinoco::ConnectionUpdatePlan {
                table_name: "Character",
                columns: &["playerId"],
                row: vec![parent.id.clone().into_dinoco_value()],
                conditions: vec![
                    dinoco::Expression::Column("id".to_string()).eq(value.clone().into_dinoco_value()),
                ],
            }],
            Self::Outfit(value) => vec![dinoco::ConnectionUpdatePlan {
                table_name: "CharacterOutfit",
                columns: &["playerId"],
                row: vec![parent.id.clone().into_dinoco_value()],
                conditions: vec![
                    dinoco::Expression::Column("id".to_string()).eq(value.clone().into_dinoco_value()),
                ],
            }],
            Self::Subscription(value) => vec![dinoco::ConnectionUpdatePlan {
                table_name: "Subscription",
                columns: &["playerId"],
                row: vec![parent.id.clone().into_dinoco_value()],
                conditions: vec![
                    dinoco::Expression::Column("id".to_string()).eq(value.clone().into_dinoco_value()),
                ],
            }],
        }
    }

    fn relation_links(&self, parent: &Player) -> Vec<dinoco::RelationLinkPlan> {
        match self {
            Self::Token(_) => Vec::new(),
            Self::Reset(_) => Vec::new(),
            Self::Verify(_) => Vec::new(),
            Self::Character(_) => Vec::new(),
            Self::Outfit(_) => Vec::new(),
            Self::Subscription(_) => Vec::new(),
        }
    }
}

impl dinoco::InsertRelation<super::player_token::PlayerToken> for Player {
    fn bind_relation(&self, item: &mut super::player_token::PlayerToken) {
        item.playerId = Some(self.id.clone().into());
    }
}

impl dinoco::InsertConnection<super::player_token::PlayerToken> for Player {
    fn connection_updates(&self, item: &super::player_token::PlayerToken) -> Vec<dinoco::ConnectionUpdatePlan> {
        vec![dinoco::ConnectionUpdatePlan {
            table_name: "PlayerToken",
            columns: &["playerId"],
            row: vec![self.id.clone().into_dinoco_value()],
            conditions: vec![
                dinoco::Expression::Column("id".to_string()).eq(item.id.clone().into_dinoco_value()),
            ],
        }]
    }
}

impl dinoco::InsertRelation<super::player_reset_password::PlayerResetPassword> for Player {
    fn bind_relation(&self, item: &mut super::player_reset_password::PlayerResetPassword) {
        item.playerId = Some(self.id.clone().into());
    }
}

impl dinoco::InsertConnection<super::player_reset_password::PlayerResetPassword> for Player {
    fn connection_updates(&self, item: &super::player_reset_password::PlayerResetPassword) -> Vec<dinoco::ConnectionUpdatePlan> {
        vec![dinoco::ConnectionUpdatePlan {
            table_name: "PlayerResetPassword",
            columns: &["playerId"],
            row: vec![self.id.clone().into_dinoco_value()],
            conditions: vec![
                dinoco::Expression::Column("id".to_string()).eq(item.id.clone().into_dinoco_value()),
            ],
        }]
    }
}

impl dinoco::InsertRelation<super::player_verify::PlayerVerify> for Player {
    fn bind_relation(&self, item: &mut super::player_verify::PlayerVerify) {
        item.playerId = Some(self.id.clone().into());
    }
}

impl dinoco::InsertConnection<super::player_verify::PlayerVerify> for Player {
    fn connection_updates(&self, item: &super::player_verify::PlayerVerify) -> Vec<dinoco::ConnectionUpdatePlan> {
        vec![dinoco::ConnectionUpdatePlan {
            table_name: "PlayerVerify",
            columns: &["playerId"],
            row: vec![self.id.clone().into_dinoco_value()],
            conditions: vec![
                dinoco::Expression::Column("id".to_string()).eq(item.id.clone().into_dinoco_value()),
            ],
        }]
    }
}

impl dinoco::InsertRelation<super::character::Character> for Player {
    fn bind_relation(&self, item: &mut super::character::Character) {
        item.playerId = Some(self.id.clone().into());
    }
}

impl dinoco::InsertConnection<super::character::Character> for Player {
    fn connection_updates(&self, item: &super::character::Character) -> Vec<dinoco::ConnectionUpdatePlan> {
        vec![dinoco::ConnectionUpdatePlan {
            table_name: "Character",
            columns: &["playerId"],
            row: vec![self.id.clone().into_dinoco_value()],
            conditions: vec![
                dinoco::Expression::Column("id".to_string()).eq(item.id.clone().into_dinoco_value()),
            ],
        }]
    }
}

impl dinoco::InsertRelation<super::character_outfit::CharacterOutfit> for Player {
    fn bind_relation(&self, item: &mut super::character_outfit::CharacterOutfit) {
        item.playerId = Some(self.id.clone().into());
    }
}

impl dinoco::InsertConnection<super::character_outfit::CharacterOutfit> for Player {
    fn connection_updates(&self, item: &super::character_outfit::CharacterOutfit) -> Vec<dinoco::ConnectionUpdatePlan> {
        vec![dinoco::ConnectionUpdatePlan {
            table_name: "CharacterOutfit",
            columns: &["playerId"],
            row: vec![self.id.clone().into_dinoco_value()],
            conditions: vec![
                dinoco::Expression::Column("id".to_string()).eq(item.id.clone().into_dinoco_value()),
            ],
        }]
    }
}

impl dinoco::InsertRelation<super::subscription::Subscription> for Player {
    fn bind_relation(&self, item: &mut super::subscription::Subscription) {
        item.playerId = Some(self.id.clone().into());
    }
}

impl dinoco::InsertConnection<super::subscription::Subscription> for Player {
    fn connection_updates(&self, item: &super::subscription::Subscription) -> Vec<dinoco::ConnectionUpdatePlan> {
        vec![dinoco::ConnectionUpdatePlan {
            table_name: "Subscription",
            columns: &["playerId"],
            row: vec![self.id.clone().into_dinoco_value()],
            conditions: vec![
                dinoco::Expression::Column("id".to_string()).eq(item.id.clone().into_dinoco_value()),
            ],
        }]
    }
}

impl Model for Player {
    type Include = PlayerInclude;
    type Where = PlayerWhere;

    fn table_name() -> &'static str {
        "Player"
    }
}

impl RelationMutationModel for Player {
    type Relations = PlayerRelations;

    fn relation_write_plan(target: dinoco::RelationMutationTarget) -> Option<RelationWritePlan> {
        match target.relation_name {
            _ => None,
        }
    }
}

impl FindAndUpdateModel for Player {
    type Update = PlayerUpdate;

    fn primary_key_columns() -> &'static [&'static str] {
        &[
            "id",
        ]
    }
}
