//! Runs project-owned Rust (`dinoco/transform.rs`).
//!
//! The CLI is a prebuilt binary and cannot load user code, so it generates a
//! tiny cargo project in `dinoco/.runner/` that `#[path]`-includes that file
//! and runs it. Set `DINOCO_RUNNER_CRATES_PATH` to a Dinoco checkout to build
//! the runner against local crates instead of the published ones.

use std::collections::hash_map::DefaultHasher;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::Path;
use std::process::Command;

use anyhow::{Context, bail};
use dinoco_compiler::Schema;

const RUNNER_DIR: &str = "dinoco/.runner";

/// `dinoco/transform.rs`, when the project customizes generated code.
pub fn transform_path() -> &'static Path {
    Path::new(dinoco_codegen::TRANSFORM_PATH)
}

pub fn has_transform() -> bool {
    transform_path().is_file()
}

/// Generates `dinoco/models/`, applying `dinoco/transform.rs` when it exists.
///
/// With a workspace, it also saves the schema it generated from into
/// `dinoco/migrations/<workspace>/schema/`.
pub fn generate_models(schema: &Schema, workspace: Option<&str>) -> anyhow::Result<()> {
    if has_transform() {
        crate::ui::info("Applying dinoco/transform.rs (building the Dinoco runner)");
        run(workspace)?;
    } else {
        dinoco_codegen::generate_models_for_workspace(schema, workspace)?;
    }

    if let Some(workspace) = workspace {
        let saved = crate::schema::save_workspace_schema(workspace)?;
        crate::ui::info(format!(
            "Schema saved to {} ({} file{})",
            crate::schema::workspace_schema_dir(workspace).display(),
            saved.len(),
            if saved.len() == 1 { "" } else { "s" }
        ));
    }

    Ok(())
}

/// Builds and runs the runner, which generates the models with
/// `dinoco/transform.rs` applied.
fn run(workspace: Option<&str>) -> anyhow::Result<()> {
    write_project()?;

    let status = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_string()))
        .args(["run", "--quiet", "--manifest-path"])
        .arg(format!("{RUNNER_DIR}/Cargo.toml"))
        .arg("--")
        .arg("models")
        .env("DINOCO_RUNNER_WORKSPACE", workspace.unwrap_or(""))
        .status()
        .context("failed to launch `cargo`; dinoco/transform.rs needs a Rust toolchain")?;
    if !status.success() {
        bail!("the Dinoco runner failed (see the output above)");
    }

    Ok(())
}

fn write_project() -> anyhow::Result<()> {
    let src = Path::new(RUNNER_DIR).join("src");
    fs::create_dir_all(&src)?;
    fs::write(Path::new(RUNNER_DIR).join(".gitignore"), "*\n")?;
    fs::write(Path::new(RUNNER_DIR).join("Cargo.toml"), render_manifest())?;
    fs::write(src.join("main.rs"), render_main())?;

    // A local checkout resolves offline against the checkout's own lockfile.
    if let Ok(root) = std::env::var("DINOCO_RUNNER_CRATES_PATH") {
        let lock = Path::new(RUNNER_DIR).join("Cargo.lock");
        let source = Path::new(&root).join("Cargo.lock");
        if !lock.exists() && source.is_file() {
            fs::copy(source, lock)?;
        }
    }

    Ok(())
}

fn render_manifest() -> String {
    let version = env!("CARGO_PKG_VERSION");
    let dependency = |name: &str| match std::env::var("DINOCO_RUNNER_CRATES_PATH") {
        Ok(root) => format!("{name} = {{ path = \"{}/crates/{name}\" }}\n", root.trim_end_matches('/')),
        Err(_) => format!("{name} = \"={version}\"\n"),
    };

    // Projects that share a `CARGO_TARGET_DIR` must not overwrite each other's
    // runner binary, so the package name is unique per project directory.
    let mut hasher = DefaultHasher::new();
    std::env::current_dir().unwrap_or_default().hash(&mut hasher);
    let mut manifest = format!(
        "# Generated by the Dinoco CLI. Safe to delete; it is recreated on demand.\n[package]\nname = \"dinoco-runner-{:x}\"\nversion = \"0.0.0\"\nedition = \"2024\"\npublish = false\n\n[workspace]\n\n[dependencies]\n",
        hasher.finish()
    );
    for name in ["dinoco", "dinoco_codegen", "dinoco_compiler"] {
        manifest.push_str(&dependency(name));
    }
    manifest.push_str("anyhow = \"1.0\"\n");
    manifest
}

fn render_main() -> String {
    String::from(
        r#"// Generated by the Dinoco CLI.
#![allow(unused)]

#[path = "../../transform.rs"]
mod transform;

fn main() -> ::anyhow::Result<()> {
    let task = std::env::args().nth(1).unwrap_or_default();
    let workspace = std::env::var("DINOCO_RUNNER_WORKSPACE").ok().filter(|value| !value.is_empty());

    match task.as_str() {
        "models" => models(workspace.as_deref()),
        other => ::anyhow::bail!("unknown runner task `{other}`"),
    }
}

fn models(workspace: Option<&str>) -> ::anyhow::Result<()> {
    let schema = ::dinoco_compiler::compile_file(std::path::Path::new("dinoco/schema.dinoco"))
        .map_err(|error| ::anyhow::anyhow!(error.to_string()))?;
    let schema = match workspace {
        Some(name) => schema.for_workspace(name).ok_or_else(|| ::anyhow::anyhow!("workspace `{name}` was not found"))?,
        None => schema,
    };

    ::dinoco_codegen::generate_models_with(&schema, workspace, &transform::transformer())?;
    println!("Rust models generated at dinoco/models/ (dinoco/transform.rs applied)");
    Ok(())
}
"#,
    )
}
